Gopkg.lock
http/query_service.go
query/csv/result.go
query/csv/result_test.go
query/functions/from_csv.go
query/influxql/influxql_encoder_test.go
query/influxql/result.go
query/influxql/transpiler.go
query/influxql/transpiler_test.go
query/query_test/query_test.go
query/query_test/test_cases/simple_max.ifql
query/query_test/test_cases/simple_max.in.csv
query/query_test/test_cases/simple_max.out.csv

There are two skipped tests in with this change. Both deal with encoding empty tables. The encoder needs to know before it encodes anything for a table it is empty or not. That should be possible to expose but will need to come later. For now all other features work.

fix(query/csv): update CSV encoders/decoders for final SPEC

---

http/server.go

It handles graceful termination by listening to signals which will be
particularly useful for commands where the sole purpose is to run an
http server.

feat(http): add common code for running an http server

---

cmd/transpilerd/main.go
http/server.go

The http package now contains a server that handles signals and proper
shutdown procedure. It has now been updated to use it.
The http package has also added a `ListenAndServe` convenience function
that is similar to the `net/http` one, but also takes in a logger and
will automatically use the most common signals when running an http
server.

feat(cmd/transpilerd): update transpilerd to use http server package

---

http/auth_service.go
http/bucket_service.go
http/errors.go
http/org_service.go
http/user_service.go
kit/errors/http.go

This also modifies the http error encoder to not include the reference
code in the `X-Influx-Error` message so it only includes the text.

feat(http): add a utility function for reading http errors

---

query/csv/result.go
query/csv/result_test.go
query/docs/SPEC.md
query/execute/block.go
query/execute/executetest/block.go
query/functions/storage/pb/reader.go
query/result.go

Using Empty the csv encoder can now correctly encode empty blocks.

fix(query): Add Empty to blocks

---

query/influxql/README.md
query/influxql/result.go
query/influxql/transpiler.go
query/influxql/transpiler_test.go

The transpiler will now yield each statement using the statement id so
the result encoder can properly order the results and encode the
statement id. This behavior is now in the transpiler spec.

feat(query/influxql): use yield name to specify the statement id

---

http/query_service.go
query/csv/result.go
query/csv/result_test.go
query/influxql/result.go
query/query.go
query/result.go

This modifies the `MultiResultDecoder` interface to accept an
`io.ReadCloser` so the `ResultIterator` can close the `io.Reader`
instead of doing it through a defer call. It then makes it so the
`Cancel()` method will close the reader or the reader will be
automatically closed when `More()` returns false.

fix(http): keep the http response body open until the result has been read

---

query/influxql/transpiler.go
query/influxql/transpiler_test.go
query/querytest/test_cases/simple_max.ifql

The latest version of influxdb has fixed whatever was wrong with the
group function so this works properly again.

fix(query/influxql): add group spec back to the transpiler

---

cmd/ifqld/main.go
cmd/influx/query.go
cmd/influx/repl.go
query/builtin/builtin.go
query/compile.go
query/complete/complete.go
query/complete/complete_test.go
query/execute/executor_test.go
query/functions/data_test.go
query/querytest/prepcsvtests/prepcsvtests.go
query/querytest/query_test.go

Now all packages wishing to consume query package can and must import
query/builtin in order to properly initialize all builtin values.

chore(query/builtin): Add package to formalize query builtin initialization

---

query/influxql/README.md
query/influxql/cursor.go
query/influxql/function.go
query/influxql/group.go
query/influxql/join.go
query/influxql/map.go
query/influxql/transpiler.go
query/influxql/transpiler_test.go

There are a few changes to how the transpiler works. The first is that
the streams are now abstracted behind a `cursor` interface. The
interface keeps track of which AST nodes (like variables or function
calls) are represented by the data inside of the stream and the method
of how to access the underlying data. This makes it easier to make a
generic interface for things like the join and map operations. This also
makes it easier to, in the future, use the same code from the map
operation for a filter so we can implement conditions.
This also follows the transpiler readme's methods and takes advantage of
the updates to the ifql language. This means it will group the relevant
cursors into a cursor group, perform any necessary joins, and allow us
to continue building on this as we flesh out …

refactor(query/influxql): follow the transpiler readme

---

query/influxql/join.go

This ensures the tests are not flaky because the output is
deterministic.
Fixes #116.

fix(query/influxql): ensure the join happens deterministically

---

http/server.go

This follows the logging style guide more correctly.

fix(http): use a duration literal for the server's shutdown timeout

---

query/control/controller.go

The previous code used RLock even though it was modifying a field. I
observed a data race locally due to concurrent access on that field.

fix(query/control): use Lock to avoid data race

---

README.md

Making it easier for interested parties to find Flux. Also linking to the best resource so far, which is @pauldix's presentation.
A couple other suggestions for discoverability (independent from the PR): 
- Once you have a blog/page on the website, link users there instead of directly to Paul's slides (always nice to land on the company page)
- you might want to setup another pointer repository at github.com/influxdata/flux for visibility. I couldn't find Flux without real sleuthing before realizing it was in here. Side note: you could end up migrating there as the project grows. In the meantime, you can turn off Issues on the repo and point people into here
Either way, I hope this helps. Congratulations on the release! 🎉

Linking to Flux from README.md

---

cmd/fluxd/main.go
cmd/influx/query.go
cmd/influx/repl.go
query/dependency.go
query/functions/storage/storage.go

This is needed for the `to` function to write to buckets in another
organization.

feat(query): add organization lookup to storage dependencies

---

http/transpiler_handler.go

This will match the /ping endpoint from the influxdb 1.x httpd service.
This endpoint is used by many of the clients that use the query service
and it will also be helpful for testing that the transpiler service is
up and working.
In the future, we will add the appropriate health endpoint that is
standard for 2.0. But, for the best compatibility, we have to return
something viable for 1.x clients.
Fixes #123.

feat(http): add a /ping endpoint to the transpiler

---

Makefile

Running "dep ensure" no longer always writes out the Gopkg.lock file.
As such if somehow Gopkg.toml has a newer modified time than Gopkg.lock
the make command would always run "dep ensure" and all other build
steps.
This change makes it explicit that after a dep ensure run that
Gopkg.lock is newer than Gopkg.toml.

fix(Makefile): Touch Gopkg.lock after dep ensure

---

http/swagger.yml

This is documentation for the 1.0 compatibility query path.

feat(http): add swagger definitions for influxql query

---

query/influxql/README.md
query/influxql/cursor.go
query/influxql/transpiler.go
query/influxql/transpiler_test.go

The transpiler should use a bucket for the `from()` call instead of the
database parameter which will likely be deprecated. The bucket that it
will read data from is `db/rp` and, if the retention policy isn't
specified, `autogen` will be used as the default.
Fixes #110.

feat(query/influxql): transpile using buckets instead of the database

---

query/ast/ast.go
query/ast/asttest/cmpopts.go
query/ast/json.go
query/ast/json_test.go
query/parser/flux.go
query/parser/flux.peg
query/parser/parser_test.go
query/parser/types.go

This commit closes #24 . It adds the syntax for optional query metadata to the Flux grammar. The Flux grammar defines this syntax strictly as variable declarations preceded by the "option" keyword.

add syntax for query metadata to Flux grammar

---

kit/errors/http.go
kit/errors/http_test.go

The `errors` package is giving back to the client the full error passed by the caller to `EncodeHTTP`.
This PR makes `EncodeHTTP` more defensive against its consumers in order to disallow error strings greater than 64 bytes.
There's not a standard in [RFC2616](https://tools.ietf.org/html/rfc2616#section-4.2) regarding the length of http headers sent back by the server, however since this implementation detail is always related to the page size of the current system (On linux see `man getpagesize`) most webservers apply restrictions on the size of the sum of the request line and all the headers, like how [nginx does](http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers) 
Said that, even if technically there's no limit in Go, boundaries, like proxies or …

Prevent X-Influx-Error headers to exceed a certain size

---

query/interpreter/interpreter.go
query/interpreter/interpreter_test.go
query/semantic/graph.go
query/semantic/graph_test.go
query/semantic/json.go
query/semantic/json_test.go
query/semantic/walk.go

This commit adds the option statement as a recognized node in
the semantic graph of a Flux query.
Flux interpreter must visit an option statement node
interpreter parses option statement

add option statement to semantic graph

---

http/transpiler_handler.go
query/csv/result.go
query/csv/result_test.go
query/influxql/result.go
query/influxql/result_test.go
query/iocounter/counter.go
query/iocounter/writer.go
query/querytest/execute.go
query/result.go

The bytes written count is used to know if an HTTP handler can safely write its own HTTP status code in the event of an error.

feat(query): Change Encode interface to return bytes written

---

http/transpiler_handler.go
query/influxql/config.go
query/influxql/transpiler.go
query/transpiler.go

The influxql transpiler can now be configured with a default database
and retention policy.

feat(query/influxql): expose default database and retention policy for transpiler

---

query/execute/transformation.go
query/id/id.go

Finishes up work started in #145, now that our internal dependencies no
longer refer to plaform/query/id.

chore(query): remove id package

---

http/status.go

This change fixes the `XXX` status classes that are present in the metrics. The `XXX` class indicate that the response writer did not know what the status code was. Based on the docs https://golang.org/pkg/net/http/#ResponseWriter we can assume a 200 was written. All status code are >= 100 so this is safe.

fix(http): Fix status class when WriteHeader was not called

---

query/influxql/group.go
query/influxql/result_test.go
query/influxql/transpiler_test.go
query/querytest/query_test.go
query/querytest/test_cases/group.flux
query/querytest/test_cases/group.influxql
query/querytest/test_cases/group.out.csv
query/querytest/test_cases/group_ungroup.influxql

The transpiler now supports grouping by tags.
Fixes #95.

feat(query/influxql): support for group by

---

query/compile.go
query/functions/join.go

These changes fix a bug where parent nodes are not **VISITED** in a consistent manner when building a query spec. Visit order is crucial for correct spec serialization as OperationIDs are assigned during the spec building phase. This fix orders parents based on the parameter name that holds them.

order parents in join based on parameter name

---

Gopkg.lock
Gopkg.toml

Problem:
Under some circumstances tdigest would panic if the quantile was before 1/2 of the mean of the first centroid.
https://github.com/influxdata/tdigest/issues/7
Solution:
Library has fix; update the vendoring

chore(vendor): update tdigest library fixing percentile panics

---

query/functions/from.go
query/functions/from_test.go

This change will enable the transpiler to create specs using IDs without having to convert back and forth between bucket names and IDs.

feat(query): Add support for using bucketID in from

---

query/functions/query_test.go
query/functions/testdata/string_interp.flux
query/functions/testdata/string_interp.in.csv
query/functions/testdata/string_interp.out.csv

Addresses #404; Adds a test for string interpolation using `filter` with an interpolated string. Currently failing.

Add flux string interpolation test

---

query/functions/difference_test.go
query/functions/testdata/difference.in.csv
query/functions/testdata/difference.out.csv
query/functions/testdata/difference_one_value.in.csv
query/functions/testdata/difference_one_value.out.csv
query/functions/testdata/difference_panic.out.csv
query/functions/testdata/meta_query_fields.in.csv
query/functions/testdata/meta_query_fields.out.csv
query/functions/testdata/meta_query_keys.in.csv
query/functions/testdata/meta_query_keys.out.csv
query/functions/testdata/meta_query_measurements.in.csv
query/functions/testdata/meta_query_measurements.out.csv

These tests were part of a PR when the rename was made.
The changes were not rebased before merge so we did not discover the
failures till after the merge.

fix: Fix tests that are failing because of the rename

---

query/builtin/builtin.go
query/compile.go
query/control/controller.go
query/functions/count_test.go
query/functions/join.go
query/functions/mean_test.go
query/functions/percentile_test.go
query/functions/prepcsvtests/prepcsvtests.go
query/functions/query_test.go
query/functions/range_test.go
query/functions/skew_test.go
query/functions/spread_test.go
query/functions/stddev_test.go
query/functions/sum_test.go
query/functions/system_time.go
query/interpreter/interpreter.go
query/interpreter/interpreter_test.go
query/options/now.go
query/plan/logical.go
query/plan/logical_test.go
query/plan/physical.go
query/plan/physical_test.go
query/query_test.go
query/querytest/compile.go
query/querytest/compspecs/compspecs.go
query/repl/repl.go
query/spec.go
query/values/function.go
query/values/values.go

This commit adds a `now` field to a query spec as well as `Now` fields to logical and physical plans. These fields represent the current system time that a query will execute with respect to. This commit is in preparation for adding an interface for getting and setting Flux options - in particular the **now** option.

set now time at query spec level

---

http/query_service.go
query/control/controller.go
query/control/metrics.go
query/execute/executor.go
query/execute/executor_test.go
query/query.go

Introduces the Statisticser interface which ResultIterators may
implement.
The HTTP implementation uses HTTP trailers to preserve the statistics.
This way we do not need to have all encoders and decoders support
statistics.

feat: Add query statistics

---

kit/signals/context.go
kit/signals/context_test.go

I'm adding various nice-to-haves in the kit package.
Here is a helper function to capture signals and receive notifications via `<-ctx.Done()`

feature(kit/signals): add standard method to capture signals with context

---

kit/cli/doc.go
kit/cli/viper.go
kit/cli/viper_test.go

This is a small simplification of cobra/viper with all the environment variables. 
See `doc.go` and the example in `viper_test.go`

feat(kit/cli): add viper simplification

---

kit/signals/context_test.go

go test examples must follow a very specific format when not referring to a specific identifier.
Namely the example name must start with "Example" followed by an underscore and lowercase letter.

go test examples must follow a very specific format

---

mock/bucket_service.go
mock/executor.go
query/control/controller.go
query/control/controller_test.go

If a query is attempting to be enqueued and it gets canceled, it will
now stop attempting to add it to the new queries queue and return the
error reported by the context. This allows the http server to cancel a
running query when the client disconnects for whatever reason without
continuing to attempt to process the canceled query.

fix(query/control): cancel the enqueue of a query if the context finishes

---

query/influxql/cursor.go
query/influxql/group.go
query/influxql/spectests/aggregates.go
query/influxql/spectests/aggregates_with_condition.go
query/influxql/spectests/aggregates_with_groupby.go
query/influxql/spectests/aggregates_with_window.go
query/influxql/spectests/aggregates_with_window_offset.go
query/influxql/spectests/math.go
query/influxql/spectests/multiple_aggregates.go
query/influxql/spectests/multiple_statements.go
query/influxql/spectests/raw.go
query/influxql/spectests/raw_with_condition.go
query/influxql/spectests/raw_with_regex_condition.go
query/influxql/spectests/retention_policy.go
query/influxql/spectests/selectors.go
query/influxql/transpiler.go

The now time is stamped by the influxql transpiler and used inside of
the actual query. It will result in more accuracy if we take the
timestamp we have created and send it as part of the spec to queryd
rather than force ourselves to ensure absolute times exist everywhere.

fix(query/influxql): influxql transpiler should set the now time

---

http/query_service.go
http/swagger.yml

Closes #470 
Problem: We needed a way to verify that a flux connection was valid before updating or creating it on the Chronograf side. 
Solution: Add a ping endpoint for fluxd.

feat(http): Add /ping endpoint to fluxd

---

.circleci/config.yml

We need to use a much larger container to test and release our master branch; it needs to include yarn and node.
goreleaser is not able to be built with node/yarn etc.
Use circles' circleci/golang:1.10.3-node-browsers container that has node, yarn and browsers for larger integration tests.

ci(deploy): nightlies use circleci/golang:1.10.3-node-browsers

---

chronograf/bolt/sources.go

On 32-bit architectures 64bit constant numbers can overflow.
Building the new sources with arm7 architecture returns a compile error.
Default source is a temporary solution anyway, so, changed to max 32-bit number.

fix(chronograf/bolt): max int64 overflows 32-bit archs

---

query/control/controller.go
query/spec.go

A transpiled query is submitted to the controller but is not produced by the Flux interpreter. Hence it cannot take advantage of the `now` option in order to set its `Now` field. The controller must explicitly check that the Now field of a query spec is set, and if not, must set it before enqueuing it.

controller sets Now time before enqueuing a query

---

Gopkg.lock
Gopkg.toml

We will now use the `platform` branch of InfluxDB, so that we can make breaking changes to the storage engine, and import them into Platform.
This is preferable to migrating code into Platform, or using a fork, as it will make it easier to keep the InfluxDB `platform` branch up-to-date with the InfluxDB `master` branch whilst the 1.7 development cycle is ongoing.

Use platform branch on influxDB

---

query/control/controller.go

Guard against nil allocator, since the allocator will only exist of the query managed to get to the execution step.
Panic on nil allocator
Guard against nill allocator

fix: Panic in query/controller on Statistics

---

query/functions/from_csv.go
query/functions/query_test.go

This uses the same code as the other end to end so we can benchmark the
entire query engine.
Related to #433, but it doesn't complete it because we should also have benchmarks for only the parser itself.

tests(query/functions): add benchmarks for all of the query tests

---

task/backend/bolt/bolt.go
task/backend/inmem_store.go
task/backend/store.go
task/backend/storetest/storetest.go

Grant access to backend task meta which should allow us to pick up where we left off in the event of a crash.

feat(tasks): add get meta to the store interface.

---

query/execute/format.go

Fixes an issue with formatting tables that was causing a panic when a column header was long.
Code that computes column widths was not taking the `:<type>` part of the column headers.
Update the logic to include the complete width of the column header.

Take into account ':<type>' when computing column header widths

---

http/external_query_handler.go
http/swagger.yml

Co-authored-by: Chris Goller <goller@gmail.com>
Query endpoint assumed that if it was application JSON, it was a spec based query instead of a regular flux query.
Add support for posting flux queries as a json body.
Add more validation.

feat(http): support posting queries as a json body

---

query/ast/ast.go
query/ast/json.go
query/ast/json_test.go
query/parser/flux.go
query/parser/flux.peg
query/parser/parser_test.go
query/parser/types.go
query/semantic/graph.go
query/semantic/graph_test.go

Closes #558 
The Flux grammar did not support day and week duration literals.
I defined new tokens for `d` and `w` in a duration literal in the Flux grammar file. I also delayed converting an abstract duration literal type to a concrete duration Go type. That conversion now takes place during the construction of a semantic graph.
To test:
* rebuild the project by running `make` from the project root
* `cd` to the bin/darwin directory
* start the Flux cli via `./influx repl`
* Enter the new duration literals to see that they are correctly parsed and interpreted
```
>1d
>24h0m0s
>
>1w
>168h0m0s
```

new duration literals

---

cmd/fluxd/README.md

The docs for the `all` metrics was missing.

update Flux metrics docs

---

query/control/controller.go
query/control/controller_test.go

The call to `setErr` would grab a lock that `Pop` used, but `setErr`
requires the controller run loop to be executing for it to work. If we
reverse the order of these calls, it should be fine.

fix(query/control): remove a deadlock

---

query/control/controller.go
query/control/controller_test.go

We decremented all, but forgot to decrement queueing when it was set and
the query spec could not be validated.

fix(query/control): fix the queueing metric

---

Gopkg.lock
query/control/controller.go
query/execute/dispatcher.go
query/execute/executor.go
query/execute/executor_test.go

The logger is now threaded into the query controller, executor, and the
dispatcher so that we can log panics. They are logged at the info level
because the panics do not result in the system crashing and becoming
unusable.

feat(query): log panics with their stacktraces within the query executor

---

cmd/fluxd/main.go
http/client.go
http/external_query_handler.go
http/handler.go
http/proxy_query_service.go
http/query_service.go
zap/auth_service.go
zap/tracer.go

Propogate opentracing spans through HTTP requests.
Use zap logger to log each span as it is finished.

feat: Add zap opentracing.Tracer

---

query/docs/SPEC.md

There are a few fundamental changes the PR introduces:
1. A `timeZone` options is added to set the context of the entire script.
2. Durations are not a single integer value, they are a set of three values: nanoseconds, days and months.
3. New types were introduced: The `interval` which is a length of time with specific start and stop dates. And the `generator` types which produce an unknown number of values. Together these concepts can represent a set of intervals of unknown size.
4. The window function accepts a set of intervals (via a generator or otherwise) that dictate how to window data.
5. The idea of `interval comprehensions` are added which allow a user to define arbitrary natural intervals of time. These comprehensions can describe fortnights, quarters, fiscal years that start in …

chore: Specify calendar intervals, windowing and time zone behavior

---

query/docs/SPEC.md

Addresses this issue https://github.com/influxdata/idpe/issues/1382
Addresses this PR https://github.com/influxdata/idpe/pull/1410
This commit proposes a new design for the `to` operation.
The current `to` operation doesn't write its data points correctly when its input table contains a `_field` column. In particular, calling
from(bucket:"my-bucket") |> range(start:-1h) |> to(bucket:"new-bucket", org:"my-org")
should write the exact same data points from my-bucket to new-bucket. Currently it does not.
Propose a new function signature and design for the `to` function such that the default behavior is as specified above, while at the same time giving the user maximum control for how they want to write …

design spec for to function

---

Gopkg.lock
task/backend/bolt/bolt.go
task/backend/coordinator/coordinator.go
task/backend/inmem_store.go
task/backend/meta.go
task/backend/meta.pb.go
task/backend/meta.proto
task/backend/meta_test.go
task/backend/scheduler.go
task/backend/scheduler_test.go
task/backend/store.go
task/backend/storetest/storetest.go
task/mock/scheduler.go
task/options/options.go
task/options/options_test.go

This is a fairly wide refactor that pushes schedule determination responsibility into StoreTaskMeta, and then replaces Store.CreateRun with Store.CreateNextRun. The work has been organized into a logical progression of commits.
The old behavior of Store.CreateRun was to just create a run for whatever timestamp was requested. The new behavior of Store.CreateNextRun is to track the runs that have been created and enforce that runs are created in the correct chronological order (via the StoreTaskMeta type).
As part of this change, a task's `delay` option is respected when scheduling a task.
This change also updates StoreTaskMeta to include new fields to handle manually requested runs (#613). Other than adding those fields, I have not yet begun work on that. Supporting manual re-runs should …

StoreTaskMeta cleanup and support for task option delay

---

query/influxql/group.go
query/influxql/spectests/math.go
query/influxql/spectests/multiple_aggregates.go
query/influxql/transpiler.go

The behavior needs to be updated so we are goinig to just disable it
temporarily so bad query specs are not generated.
Related to #707.

fix(query/influxql): disable the join behavior in the transpiler

---

http/swagger.yml

Token permissions are immutable, but, it would be nice to enable/disable tokens rather than just DELETE them.
_What is the problem?_
Administrators should have the ability to temporarily disable a token (perhaps the writes using a token are hurting the system).
Once the issue has been resolved the token can be enabled.  This way the token doesn't need to be DELETED, but, just disabled.
My first boolean!! I feel like it is legit in this case that a token only has 2 states.

docs(http): add disabled boolean for authorization tokens

---

task/backend/inmem_logreaderwriter.go
task/backend/scheduler_test.go

In TestScheduler_RunLog, the run log gets updated asynchronously so we
need to poll to ensure we don't read a stale value.
In TestScheduler_CreateNextRunOnTick, we were previously reading the
one entry out of two from a map, so it was often the entry we weren't
interested in.

test(task): fix two flaky tests

---

query/influxql/response_iterator.go
query/influxql/response_test.go

This PR implements `query.ResultIterator` on `influxql.Response`. The motivation behind this is so that chronograf can issue queries to v1.X InfluxDB instances and return 2.X style csv results.
TODO:

Implement query.ResultIterator on influxql.Response

---

task/adaptertest/adaptertest.go
task/backend/bolt/bolt.go
task/backend/inmem_logreaderwriter.go
task/backend/inmem_store.go
task/backend/storetest/logstoretest.go
task/platform_adapter.go
task/platform_adapter_test.go

Also fix a handful of segfaults caused by improperly retained byte slices
from bolt, and combine two view transactions into one to avoid a data
race when a delete happened between them.

test(task): add platform adapter tests

---

cmd/influxd/main.go
http/external_query_handler.go
http/handler.go
http/health.go
http/platform_handler.go
http/query.go
http/query_handler.go
http/requests.go
http/write_handler.go
zap/proxy_query_service.go

Closes #
Add /v2/query to handle flux queries
Queries are important to a database.
We added a handler for flux queries.  Currently, the handler just prints out the queries. 
Adding the real flux engine probably requires storage.

feat(http): add flux endpoint /v2/query influx

---

kit/cli/viper.go
kit/cli/viper_test.go

Need boolean and duration type flags.
Add a types to `kit/cli/viper.go`

kit/cli: Add boolean and duration flag types

---

dashboard.go
error.go
errors.go
errors.md
errors_test.go
source.go
view.go

https://github.com/influxdata/idpe/issues/488
This is a global errors library. Ideally, we could make all of our generated errors have type and location, 
and wrap all the third party errors with references.
Due the complexity of our current code base. We decide to separate this project to small PRs. After the library been pushed. We could use this lib for all the new errors, then gradually update our existing code structure.

feat(errors): add error lib

---

Gopkg.toml

The query package has now mostly been moved to influxdata/flux so these
constraints cause dep to print a non-useful message that is confusing.

fix: remove constraints that were from the query package

---

Makefile

Add path to the makefile
go-bindata is not found
Use export extension of GNU Make

ci(Makefile): update PATH to have go-bindata

---

Makefile
chronograf/ui/Makefile
chronograf/ui/package.json

Move asset generation into ui directory
dist_gen.go was running before the assets had been created
Created a makefile in the ui directory that is called by the top-level makefile

ci(Makefile): add asset generation to nightly

---

chronograf/ui/src/flux/apis/index.ts
chronograf/ui/src/flux/components/FilterArgs.tsx
chronograf/ui/src/flux/components/FilterPreview.tsx
chronograf/ui/src/flux/containers/FluxPage.tsx
cmd/fluxd/main.go
http/flux_lang.go
http/flux_lang_test.go
http/query.go
http/query_test.go
mock/org_service.go

Add support for AST and Spec generation as well as query support of AST and spec.
1. Use influxdb nightly from https://portal.influxdata.com/downloads
2. run `influxd config > influxd.conf`
3. run `influxd -config influxd.conf`
4. __must__ have influxd running before turning on fluxd.
5. Download fluxd nightly from https://portal.influxdata.com/downloads
6. `run fluxd --storage-hosts 127.0.0.1:8082`
7. install and run telegraf to get data into influx
Produce AST JSON structure of flux by POSTing to the `/v2/flux/ast` endpoint:
```sh
curl -XPOST http://127.0.0.1:8093/v2/flux/ast -d '{"query": "from(bucket: \"telegraf\")"}'
```
```sh
curl -XPOST http://127.0.0.1:8093/v2/flux/ast -d '{"query": "from(bucket: \"telegraf\")"}' > ast.json
curl -v -XPOST …
```

feat(http): add flux AST and Spec endpoints to fluxd

---

inmem/auth_service.go
inmem/auth_test.go
inmem/bucket_service.go
inmem/bucket_test.go
inmem/dashboard.go
inmem/dashboard_test.go
inmem/dbrp_mapping_service.go
inmem/dbrp_mapping_test.go
inmem/organization_service.go
inmem/organization_test.go
inmem/service.go
inmem/user_resource_mapping_service.go
inmem/user_service.go
inmem/user_test.go
inmem/view.go
inmem/view_test.go

Copy in-memory services into platform for use in testing.
To simplify testing here is an in-memory implementation of the services.

feat(inmem): add in-memory service implementations

---

chronograf/ui/src/flux/apis/index.ts

Add defaults for AST response.
If there was no `ast` in the returned object, it would thrown an error.
Using getDeep (lodash wrapper)

fix(flux/api): ensure ast default

---

Gopkg.lock
Gopkg.toml
Makefile

Nightlies are not being uploaded to  s3, this is because a recent update to Goreleaser made it so that snapshots are not published. This PR to goreleaser allows for publishing snapshots https://github.com/goreleaser/goreleaser/pull/805
This PR uses our fork of goreleaser to get nightlies working again.

chore: Update GoReleaser to publish snapshots

---

http/proxy_query_service.go
http/query_handler.go
http/query_service.go

Since all paths for the various query services were the same even though
the API are different it was confusing to work with and debug.
Now all internal paths have a unique name.

fix: Update internal HTTP paths for query service

---

Makefile

This was mistakenly deleted when I deleted vendor. I have no idea why it
was deleted so it was probably a mistake or something left over from
testing.
Fixes #858.

fix: restore the generate task in the Makefile

---

bolt/bbolt_test.go
bolt/user.go
bolt/user_test.go
go.mod
user.go

Closes #856
This PR introduces a service that can store users passwords securely (with bcrypt). It does implement any authentication or authorization.

Add basic authentication service

---

http/query_handler.go

Fixes issue of missing Org parameter in FluxQueryService client.

Flux Pass org parameter

---

bucket.go
cmd/influx/bucket.go
http/bucket_service.go
http/bucket_test.go
http/duration.go
http/duration_test.go

Note: I'll create a follow-on PR for changing the external format of the time duration from a string to an object.  I think this set of changes should be reviewed first before I plunge into an entirely different structure.
Closes #796
Change bucket retention periods from nanoseconds to influxql-style duration strings.
Nanoseconds are difficult to use and a bit unpleasant to view.
retention period is now a string in the influxql duration format.
/cc @gshif

feat(http): buckets now use influxql duration strings

---

Makefile

Closes #
With go modules the go build system takes a few environment variables.  Goreleaser uses those variables to configure the go build.
`goreleaser` needs the various go environment variables to run properly.
Added the variables and tested it in circle's ssh.

ci(goreleaser): add new go env vars to goreleaser

---

.goreleaser.yml
Makefile
http/assets.go

Closes #
To override goreleaser build tags properly, one must pass the flags option in the releaser yaml.
The release binaries did not have the static assets compiled in.
Rather than the makefile passing go modules environment to goreleaser, update goreleaser.yaml to cinclude

ci(goreleaser): override goreleaser build flags

---

bolt/bbolt.go
bolt/session.go
bolt/session_test.go
http/session_handler.go
http/session_test.go
http/swagger.yml
mock/basic_auth.go
mock/session_service.go
session.go
testing/session.go

Closes #890
This PR adds a session service that is intended to be used after a user has authenticated. A session should represent a users maximal privileges, although this has yet to be fully worked out. It contains an ID so that it will be auditable.
This PR adds `/signin` and `/signout` routes that allow the user to exchange basic auth credentials for a session.

Add routes that allow the user to exchange basic auth credentials for a session

---

chronograf/ui/src/dashboards/apis/v2/index.ts
chronograf/ui/src/shared/apis/links.ts
chronograf/ui/src/sources/apis/v2/index.ts

Closes #
API routes were changed to `/api/v2` from `/v2`
Make changes on the FE to get links and sources from `api/v2` instead of `/v2`

Convert everything to /api/v2 on the FE

---

auth.go
authz.go
cmd/influxd/main.go
context/token.go
http/api_handler.go
http/authentication_middleware.go
http/authentication_test.go
http/errors.go
http/platform_handler.go
http/query_handler.go
http/session_handler.go
http/session_test.go
http/write_handler.go
query/preauthorizer.go
session.go
task/validator.go

Note: this will enforce authentication for all routes except for the following
* `/metrics`
* `/healthz`
* `/debug/pprof/*`
* `GET - /api/v2`
* `POST - /api/v2/setup`
* `POST - /api/v2/signin`
* `POST - /api/v2/signout`
Closes #926
This PR adds support for authenticating requests that provide either a token or a valid session.
Additionally it provides a refactor that allows wrapping the API related parts of the platform handler.

Add authentication middleware

---

gather/scheduler.go
gather/scheduler_test.go
gather/scraper_test.go
mock/nats.go
mock/nats_test.go

Closes #
https://github.com/influxdata/platform/issues/851
Previously, we use real nats server for testing, assuming it will work. This fix will use a mocked Nats Server, which is a simple map of go channels. So we won't rely on nats processing speed.

try to restore the test

---

http/swagger.yml
view.go

Closes #918
Add LogView configuration as a new view type.
Previously in the last episode of chronograf, our adventurers used `/chronograf/v1/org_config/logviewer` to store the view state of log viewer.  Now we have a generic `/views` endpoint to handle such things.
(see https://github.com/influxdata/chronograf/blob/master/chronograf.go#L876-L893 for previous impl)
We ported the org_config struct from chronograf with minor changes ('encodings` is now `settings`).

feat(http/view): add storing LogView config

---

query/influxql/service.go
query/influxql/service_test.go

It creates a simple client that follows the QueryService interface and
uses the `influxql.Compiler` type to determine where the query should be
routed to and to return the query as a `flux.ResultIterator`.
This will be useful for replaying transpiler queries against influxdb
1.x servers to verify correctness.

feat: add an influxql service that communicates with influxdb 1.x

---

http/query_handler.go
http/write_handler.go

The authorization changes made it so that we no longer call `SetToken`, so these handlers that called `GetToken` were failing. Change them to call `GetAuthorizer` and pass the id to the `AuthorizationService` instead of the token.

Change how the write and query handlers look at auth

---

chronograf/ui/src/clockface/components/component_spacer/ComponentSpacer.scss
chronograf/ui/src/clockface/components/panel/Panel.scss
chronograf/ui/src/clockface/components/panel/Panel.tsx
chronograf/ui/src/clockface/components/panel/PanelFooter.tsx
chronograf/ui/src/clockface/components/panel/PanelHeader.tsx
chronograf/ui/src/clockface/index.ts

Simplify design and associated components of `Panels` Clockface component.
No longer has a `type` prop and appears much more compact. Deleted a bunch of styles that don't need to exist.

Redesign Panels to conform to 2.0 UI Patterns

---

http/handler.go

We should not log fields that don't exist since it clutters up the logs.

fix(http): only log an error and reference code if it exists

---

cmd/influxd/extra.go
cmd/influxd/main.go
storage/config.go
storage/engine.go
storage/series_cursor.go
tsdb/config.go
tsdb/explode.go
tsdb/index.go
tsdb/index/tsi1/config.go
tsdb/index/tsi1/file_set_test.go
tsdb/index/tsi1/index.go
tsdb/index/tsi1/index_test.go
tsdb/index/tsi1/partition.go
tsdb/index_test.go
tsdb/series_file.go
tsdb/shard.go
tsdb/shard_test.go
tsdb/tsm1/engine_test.go

Closes #884
This PR adds an initial storage engine, which comprises: a TSM engine, a SeriesFile and a TSI index.
We didn't have a storage engine
Write a storage engine.
There is still a huge amount of work I need to do, but this should give us a working storage engine that snapshots on every write. It should be enough for the Chronograf team to use as a backend for their development.

Add storage engine

---

chronograf/ui/mocks/dummy.ts
chronograf/ui/src/Signin.tsx
chronograf/ui/src/index.tsx
chronograf/ui/src/onboarding/apis/index.ts
chronograf/ui/src/onboarding/components/AdminStep.tsx
chronograf/ui/src/onboarding/containers/SigninPage.tsx
chronograf/ui/src/shared/copy/notifications.ts
chronograf/ui/src/shared/reducers/links.test.ts
chronograf/ui/src/shared/reducers/links.ts
chronograf/ui/src/types/v2/links.ts
chronograf/ui/src/utils/ajax.ts

Closes #[110](https://github.com/influxdata/applications-team-issues/issues/110)
Onboarding wizard retrieves cookie session token from /signin after completing setup
After setup has been completed, user is prompted for username&password, and signin flow retrieves cookie session. 
ATTN: THis is a hacky solution to get us able to work on platform, will refactor this flow later with more time

Signin after setup

---

query/promql/Makefile
task/backend/Makefile

`make run` currently fails if you have anything in `PATH` with spaces, this change handles those cases

Properly handle spaces in PATH with make tasks

---

bolt/dashboard.go
bolt/user_resource_mapping.go
dashboard.go
http/dashboard_service.go
http/swagger.yml
inmem/dashboard.go
inmem/user_resource_mapping_service.go
mock/user_resource_mapping_service.go
testing/dashboards.go
testing/user_resource_mapping_service.go
user_resource_mapping.go
user_resource_mapping_test.go

`GET /dashboards` now takes `ids` and `owner` params, so that a request can filter on dashboards that belong to an owner, or a slice of dashboard ids.
closes #924.

Filter dashboards by owner

---

bolt/user.go
testing/user_service.go

Check for null bytes returned by index in bolt users.
Null bytes are decoded into invalid IDs returning an incorrect error for unknown users.
Check for null bytes and return the user is not found.  Also, added tests for a user not found.

fix(bolt): handle user not found error

---

query/functions/inputs/storage/storage.go

Closes #
Add `Database` and `RetentionPolicy` fields to the `storage.ReadSpec` struct
The `platform.ID` type was changed from `[]byte` to `uint64`. Previously, InfluxDB was using the `ReadSpec.BucketID` field to encode the database and retention policy for a `from` request. This is no longer possible in a `uint64`, which prevents any future updates to the flux and platform repositories in influxdb OSS.
Adding `Database` and `RetentionPolicy` fields to the `storage.ReadSpec` struct permits the OSS implementation of Flux to assign Database and RetentionPolicy values.

fix(storage): Add db/rp fields for InfluxDB OSS

---

chronograf/ui/src/dashboards/components/VEO.tsx
chronograf/ui/src/dashboards/components/VEOHeader.tsx
chronograf/ui/src/dataExplorer/components/DataExplorer.tsx
chronograf/ui/src/dataExplorer/components/DataExplorerPage.tsx
chronograf/ui/src/shared/actions/v2/timeMachines.ts
chronograf/ui/src/shared/components/RefreshingView.tsx
chronograf/ui/src/shared/components/TimeMachine.scss
chronograf/ui/src/shared/components/TimeMachine.tsx
chronograf/ui/src/shared/components/TimeMachineTabs.tsx
chronograf/ui/src/shared/components/ViewTypeSelector.scss
chronograf/ui/src/shared/components/ViewTypeSelector.tsx
chronograf/ui/src/shared/components/threesizer/Division.tsx
chronograf/ui/src/shared/components/threesizer/Threesizer.tsx
chronograf/ui/src/shared/reducers/v2/timeMachines.ts
chronograf/ui/src/style/chronograf.scss

Connects https://github.com/influxdata/platform/issues/1038
You can now render a visualization with dummy data in the CEO and DE. 
Clicking on the Visualizations tab will show a graph type selector. 
Only dygraph graph types will work right now.

Add Veo line graph and switching types

---

http/swagger.yml
telegraf.go
telegraf/plugins/inputs/base.go
telegraf/plugins/inputs/cpu.go
telegraf/plugins/inputs/disk.go
telegraf/plugins/inputs/diskio.go
telegraf/plugins/inputs/docker.go
telegraf/plugins/inputs/file.go
telegraf/plugins/inputs/inputs_test.go
telegraf/plugins/inputs/kernel.go
telegraf/plugins/inputs/kubernetes.go
telegraf/plugins/inputs/logparser.go
telegraf/plugins/inputs/mem.go
telegraf/plugins/inputs/net.go
telegraf/plugins/inputs/net_response.go
telegraf/plugins/inputs/ngnix.go
telegraf/plugins/inputs/processes.go
telegraf/plugins/inputs/procstats.go
telegraf/plugins/inputs/prometheus.go
telegraf/plugins/inputs/redis.go
telegraf/plugins/inputs/swap.go
telegraf/plugins/inputs/syslog.go
telegraf/plugins/inputs/system.go
telegraf/plugins/inputs/tail.go
telegraf/plugins/outputs/base.go
telegraf/plugins/outputs/file.go
telegraf/plugins/outputs/influxdb_v2.go
telegraf/plugins/outputs/outputs_test.go
telegraf/plugins/type.go
telegraf_test.go

Closes #https://github.com/influxdata/platform/issues/1096
Removed Name, Type from TelegrafPlugin struct, to prevent bad GRPC request, when the plugin name and type doesn't match Config Interface. The original JSON request and store keeps same.
Added additional PluginName(), and Type() method to each plugin.
Moved TelegrafPluginType to telegraf/plugins package to prevent cycle import
fixed swagger configs to config

add json telegraf config

---

storage/engine.go
tsdb/series_file.go
tsdb/tsi1/index.go
tsdb/tsi1/index_test.go
tsdb/tsi1/log_file.go
tsdb/tsi1/partition.go
tsdb/tsi1/stats.go
tsdb/tsi1/stats_test.go

Adds per-measurement cardinality stats to the TSI1 index.
We need to quickly be able to fetch the number of series for every measurement in the system.
This commit adds `MeasurementCardinalityStats` to `tsi1.Index`. The stats are maintained in each partition and all stats not in the non-active log file are written to disk on every compaction. At query time, every partition merges the non-active log file stats and the active log file stats and then the index merges every partition stats.
_Note: I need to rework the `LogFile` stats computation because there is a race condition where a series inserted and deleted in the same log file is double decremented.

Add tsi1 measurement cardinality stats.

---

tsdb/tsm1/reader.go

Fix call to `MeasurementStats.ReadFrom(io.Reader)`
`MeasurementStats.ReadFrom(io.Reader)` takes a `ByteReader`, but we were calling with a `Reader`.
Wrap the Reader in `bufio.NewReader`

storage: MeasurementStats.ReadFrom requires ByteReader

---

chronograf/ui/src/logs/components/loading_status/LoadingStatus.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/176
The loading message is centered using the alignment and empty state clockface components
The component was previously expecting a `generic-empty-state` class to center itself
Utilize the clockface components for empty state and alignment instead.

Fix loading empty state

---

chronograf/ui/src/logs/actions/index.ts
chronograf/ui/src/logs/api/v2/index.ts
chronograf/ui/src/logs/utils/fixtures/fluxResponse.ts
chronograf/ui/src/logs/utils/fluxResponse.test.ts
chronograf/ui/src/logs/utils/index.ts

Closes https://github.com/influxdata/applications-team-issues/issues/173
Implements the `executeQueryAsync` util to fetch logs and then sets a search status.
Logs would fail to parse in Firefox using `getTimeSeries`
Implement the ported util `executeQueryAsync` as part of `logs/api/v2`

fix(logs/fetch): add execute queries

---

http/bucket_service.go
http/bucket_test.go
http/swagger.yml

Closes #
Bucket retentions are now rules.  Currently, only one rule is allowed, but, this gives us flexibility in the future.  No rules indicate infinite retention.
Retention policies were time durations and were not flexible enough to express more than one rule
Many rules and rule types

feat(http): buckets now have multiple retention rules

---

bolt/bbolt.go
bolt/dashboard.go
bolt/dashboard_test.go
dashboard.go
http/dashboard_service.go
http/dashboard_test.go
http/swagger.yml
inmem/dashboard.go
inmem/dashboard_test.go
inmem/service.go
mock/dashboard_service.go
testing/dashboards.go

Closes #1098
This PR introduces the meta fields `CreatedAt` and `UpdatedAt` to dashboards. Additionally it allows the user to specify if they would like to sort the results by those fields.

Add CreatedAt and UpdatedAt fields to dashboards

---

bolt/bucket.go
bolt/dashboard.go
bolt/user.go
bolt/view.go

When a resource is deleted, we need to make sure that its associated u/r mappings are purged. This PR fixes that.

feat(bolt): clean up user resource mappings after deleting resources

---

cmd/influx/write.go
http/errors.go
http/write_handler.go
models/points.go

Closes #1202 
Add query parameter `precision` to be specified for writing line protocol to the server.
Swagger definition had precision, but, it was not yet supported.
Add precision support of:
- ns (default)
- n
- us
- u
- ms
- s
Note this is different than influxdb 1.x as it supported minutes and hours.

http(write): support timestamp precision

---

cmd/influx/write.go

Fix typos in the write command for precision

fix(cmd/influx): typos in cli variables

---

.circleci/config.yml

Remove the go race tests in circle ci.
We think we are being OOM-killed as our plan as 4 GB of ram.
Comment out circle race tests

ci(tests): remove go race tests from circle

---

bolt/bbolt.go
bolt/bbolt_test.go

Closes #1207 
Create directory for data if it does not already exist
If the directory was not yet created, bolt's creation would fail.
Create directory with permission 700 before open/create of bolt.

fix(bolt): create bolt/data dir if not exist

---

http/errors.go
http/org_service.go
http/scraper_service.go
http/source_service.go
http/task_service.go
http/user_service.go
task.go

Closes #170
`DELETE` of resources all return 204 for now (as is in the swagger).
In the future we may have 202's to designate asynchronous operations that can take a while before completing such as the deletion of a bucket.
Inconsistent usage of status codes for DELETE of resources
Add checks for status codes and unify status codes to be 204 for DELETEs.
This should change in the future when we have real async operations.

fix(http): all DELETEs now return 204

---

cmd/influxd/main.go
storage/engine.go
tsdb/tsi1/index.go

These are the log messages that get printed immediately when starting
the application for the first time. This fixes the messages to conform
to the logging style guide.

fix: conform to logging style guide for initial log messages

---

bolt/bbolt.go
cmd/influxd/main.go
gather/scheduler.go
http/handler.go
nats/server.go

1. use kit for viper and signals
2. close all services for clean shutdown
3. add `log-level` flag to see requests
influxd main was a bit wild.  Not all services were closed on exit. No requests were being logged.

Clean up influxdb main

---

bolt/bbolt.go
bolt/keyvalue_log.go
bolt/keyvalue_log_test.go
example_test.go
keyvalue_log.go
testing/keyvalue_log.go

Closes #1233 
This PR introduces an abstract interface that can be used to create logs of key value pairs. The intention for this is to implement an audit log as well as an operation log for all stored resources. Additionally it is intended that this log be used to update the `meta` fields associated with a resource.
This originally started out as an oplog, but was made more general.

WIP: Add keyvalue log - basis for auditlog and oplog

---

storage/reads/reader.go
storage/reads/table.go

During read operations, certain error conditions may result in storage resources not being closed. In most cases this leads to dangling references to TSM files, which cause the process to hang on shutdown or TSM files to leak after compactions. The PR ensures that all the `handle` methods correctly close these resources prior to returning.

Ensure storage resources are cleaned up

---

storage/reads/reader.go
storage/reads/table.gen.go
storage/reads/table.gen.go.tmpl
storage/reads/table.go

Previously, `Close` was being called concurrently by multiple goroutines, resulting in a race condition. This commit resolves those issues.
The `Close` method was performing multiple duties, closing resources and triggering that the table reader, via the `Do` method, was done.
Additionally, state to track whether more records existed and if the table was empty was ported from the more complicated gRPC implementation. This logic has been simplified.
This new behavior:
* `table#Do` is responsible for triggering it is done, by closing the done channel
* The creator of the `table` is responsible for releasing the resources by calling the `table#Close` method
* The `table#Do` reading can be cancelled by calling the `Cancel` function, which is safe for concurrent use.
* the `Do` and `Close` …

Fix race condition as `Close` was called by multiple goroutines

---

cmd/influxd/main.go
http/query_service.go

This adds open tracing for http endpoints for tasks and query.  Originally it was just my intent to add it for tasks, but then I realized it would be useful for query too, as both will often be behind backend software for a lot of people.
WIP

open tracing context handling for tasks and for HTTP endpoints for tasks and query

---

bolt/bucket.go
bolt/dashboard.go
bolt/organization.go
bolt/user.go
cmd/influxd/main.go
dashboard.go
http/api_handler.go
http/bucket_service.go
http/bucket_test.go
http/dashboard_service.go
http/dashboard_test.go
http/org_service.go
http/user_service.go
operation_log.go

Closes #1233 
**Briefly describe your proposed changes:**
I'd like to get some initial feedback
**What was the problem?**
We want a way to view the history of operation against a resource. It is not entirely clear what specific values should be saved for each operation. I imagine we'll want some sort of plaintext description of what happened, but I'm not sure.
One concern that I have is that the log will likely consume more disk than the resource does and I think simply having a plaintext record of what took place may not be as valuable as having a way to undo the operation that took place.
**What was the solution?**
We use the key value log to store a each event that takes place for a resource.
**TODO**

WIP: add operation log for resources

---

cmd/influx/authorization.go
cmd/influx/bucket.go
cmd/influx/main.go
cmd/influx/organization.go
cmd/influx/query.go
cmd/influx/repl.go
cmd/influx/setup.go
cmd/influx/task.go
cmd/influx/user.go
cmd/influxd/main.go
internal/fs/influx_dir.go

This PR adds a local flag to the `influx` command that works with the data directly in the filesystem.
People have been regularly losing their tokens and do not have a way to retrieve them.
Add a local flag that allows users to interact directly with a local influxdb file.
Add support for:

Add local flag to influx command

---

http/swagger.yml

Closes #
Declared parameter `userID` in path `/users/{userID}/password` but not in parameters block.
add userID parameter

fix(http): add userID parameter

---

ui/src/shared/components/TimeSeries.tsx
ui/src/utils/restartable.test.ts
ui/src/utils/restartable.ts

_Problem:_
A `TimeSeries` component fetches time series data according to its props, and provides the data to its children once it has been fetched.
If the props are updated in quick succession, multiple requests for data are issued concurrently. These requests may resolve in an order different than the order in which they were issued, resulting in stale data being provided to the children.
Since the status of each request is represented by a `Promise`, no idiomatic solution exists for canceling old requests.
_Solution:_
Introduce a `restartable` utility for wrapping a `Promise`-returning function. This utility ensures that when multiple pending promises for a function exist, 
- Only the last issue promise can resolve successfully
- Every other promise will be rejected with a …

Eliminate race condition in TimeSeries component

---

storage/engine.go
storage/engine_test.go
tsdb/tsm1/engine.go

We were passing a non-nil `tsm1.Log` containing a nil `*tsm1.WAL` which
would cause a panic when it was attempted to be used. Instead, always
pass a non-nil WAL.
We change the storage engine code to not pass in a nil WAL, and
additionally add a defensive check to change any nil WALs into a
`NopWAL`.

fix(storage): allow disabling the WAL

---

storage/engine.go

Looks like a 'continue` is missing here.

fix(storage): missing `continue`

---

task/backend/scheduler.go

Pass open tracing spans through the context from tasks to the query engine.

opentracing

---

pkg/encoding/simple8b/encoding.go
pkg/encoding/simple8b/encoding_test.go
tsdb/tsm1/compact.gen.go
tsdb/tsm1/compact.gen.go.tmpl
tsdb/tsm1/compact_test.go

This PR brings in commits from InfluxDB https://github.com/influxdata/influxdb/pull/10479 to the 2.0 engine.
An encoding bug could cause certain compressed data to be incorrectly written in the case that there were 120 or 240 values in a row that all were 1, and were to be compressed with `simple8b`. This bug is quite hard to trigger, but most commonly was triggered by some sets of evenly spaced timestamps that were then delta encoded and compressed with `simple8b`.

Fix encoding bug that could tie up compactions

---

ui/src/clockface/components/radio_buttons/RadioButtons.scss
ui/src/clockface/components/radio_buttons/RadioButtons.tsx
ui/src/clockface/styles.scss

Unless there are at least 3 items in a radio button set, it is very difficult to tell which is the selected item
Re-styled the radio buttons to look less like text inputs and have a more obvious active state by default. Radio buttons use the `Primary` theme by default which makes them blue

Improve Usability of Radio Buttons

---

ui/src/tasks/actions/v2/index.ts
ui/src/tasks/api/v2/index.ts
ui/src/tasks/components/TaskRow.tsx
ui/src/tasks/components/TasksHeader.tsx
ui/src/tasks/containers/TasksPage.tsx
ui/src/tasks/reducers/v2/index.ts

Closes #1369 
_What was the solution?_ Added a toggle on task header for option to show only active tasks.

Added toggle on Task Header for option to show only active

---

bolt/telegraf.go
inmem/telegraf.go
testing/telegraf.go

Closes https://github.com/influxdata/platform/issues/1390
Currently if no telegraf configs was in db, it will return 404 not found error.
As chronograf team points out, we should not return an empty array without error.

fix 404 to an empty array

---

bolt/bbolt.go
bolt/secret.go
bolt/secret_test.go
secret.go
testing/secret.go

Closes #1364
This PR introduces a service for storing user secrets. The current implementation stores secrets as base64 encoded strings. This is marginally better than plaintext. A follow up to this work will be to offer the ability to store these secrets in vault instead.

Add secret service interface and boltdb implementation

---

ui/src/tasks/components/TaskRow.tsx

Closes #1370 
_What was the solution?_ Task Row has an export button to export the flux in .flux extension

Add export button on task row

---

ui/src/tasks/actions/v2/index.ts
ui/src/tasks/components/TasksHeader.tsx
ui/src/tasks/components/TasksOrgDropdown.tsx
ui/src/tasks/constants/index.ts
ui/src/tasks/containers/TasksPage.tsx
ui/src/tasks/reducers/v2/index.ts

Closes #1372 
_What was the solution?_Created a dropdown on Task Header to show all organizations and an ability to filter tasks using the dropdown

Create a dropdown filter to filter tasks through Organizations

---

ui/src/tasks/components/TaskRow.tsx

Closes #1373
_What was the solution?_ Add onclick on the organization on task row direct to the organization page

Add onclick to organization on task row

---

Makefile
query/Makefile
query/promql/Makefile
task/Makefile
task/backend/Makefile

Closes #1451 
Remove clean targets for autogenerated code 
We used to not have the files in source control and these targets went stale.
Remove all the cleaning of those autogenerated files.

fix(Makefile): remove old clean targets

---

http/source_service.go
http/source_service_test.go

Closes #1425
Sources that are "self" link to /api/v2
Self-sources links did not resolve
Linking back to the top-level API
Now, we could remove self-sources altogether and rename sources to remotes.  For now this will solve the bug.
Here is an example of the response:
```json
{
"sources": [
{
"id": "020f755c3c082000",
"organizationID": "50616e67652c206c",
"default": true,
"name": "autogen",
"type": "self",
"url": "",
"telegraf": "",
"token": "",
"defaultRP": "",
"links": {
"buckets": "/api/v2/buckets",
"health": "/api/v2/health",
"query": "/api/v2/query",
"self": "/api/v2/sources/020f755c3c082000"
}
}
],
"links": {
"self": "/api/v2/sources"
}
}
```

feat(http): self sources now return links to /api/v2

---

errors.go
http/errors.go
http/swagger.yml
kit/grpc/errors.go
kit/grpc/errors_test.go

Closes #
Add new kit library to standardize translate between gRPC status errors and platform.Errors.
gRPC services have a "status" error that is returned.  We need to translate them to our standard error format.
Translates between gRPC status errors and platform.Error

feat(kit/grpc): add translation between gRPC status and platform.Error

---

authz.go
http/query.go
http/query_handler.go
http/query_test.go
query/bridges.go
query/logger.go
query/request.go
task/backend/query_logreader.go

As a result of pr https://github.com/influxdata/platform/pull/1494, idpe
broke. This PR undoes some of the work done from that PR, but fixes the
underlying issue with #1494.

fix(platform): keep authorization struct on proxy query request

---

http/org_service.go

The `org_service newDeleteMemberHandler` doesn't delete members and a `url missing member id` error is produce.
Changing the mapping from a `organizationID ` to a `userID` according to implementation of [decodeDeleteMemberRequest](https://github.com/influxdata/platform/blob/b2afb98f7c2d4dfbce12757c0beb37705e585223/http/user_resource_mapping_service.go#L206).

Fixed the organizations members paths

---

http/user_resource_mapping_service.go

The `user_resource_mapping_service` return only the `platform.Member` user mappings.
Use the `userType` parameter to filtering user resource.

fix GetMembersHandler

---

query/influxql/function.go
query/influxql/transpiler_test.go

Closes #1488 
No support for median in transpiler
Fake the median for a 50th percentile.  
The side effect on the AST could cause problems. In that case, I will update the code to treat the median as a percentile only when creating the opSpec in `createCursor`

Support for median in transpiler

---

tsdb/index_test.go
tsdb/tsi1/index.go
tsdb/tsm1/engine.go
tsdb/tsm1/engine_test.go

Updates #896
It seems that the role of `CreateSeriesIfNotExists` method has been replaced by `CreateSeriesListIfNotExists` .

Remove Index.CreateSeriesIfNotExists

---

cmd/influx/task.go
http/swagger.yml
http/task_service.go
task.go
task/backend/bolt/bolt.go
task/backend/inmem_store.go
task/platform_adapter.go

https://github.com/influxdata/platform/blob/master/task/platform_adapter.go#L45-L48
Currently, the `FindTasks` method uses a fixed `pageSize` to filter tasks.
The number of tasks to return should be specified by callers.
Update swagger to include limit param.
Add limit field to `TaskFilter`.

fix(task): add limit field to TaskFilter

---

cmd/influx/task.go
http/task_service.go
inmem/onboarding.go
mock/task_service.go
task.go
task/platform_adapter.go
task/servicetest/servicetest.go

Remove requestedAt param from the retry api call
closes #1589

remove requestedAt param from retry call

---

ui/src/clockface/components/wizard/ProgressBar.tsx
ui/src/onboarding/components/CompletionStep.tsx
ui/src/onboarding/containers/OnboardingWizard.tsx

Closes #1661
Previously, the progress bar was hidden for the last step of the onboarding process (the "completion" step). This PR will show the progress bar for this step.
(Note: displaying the progress on the green bar will be fixed in another PR.)

Add completion step to progress bar in onboarding wizard

---

http/cur_swagger.yml
ui/src/api/api.ts
ui/src/onboarding/apis/index.ts
ui/src/onboarding/components/selectionStep/SelectDataSourceStep.tsx
ui/src/onboarding/reducers/dataLoaders.test.ts
ui/src/types/v2/dataLoaders.ts

The generated client was not getting some needed type safety that the onboarding wizard needs.
Change the way the plugin types are defined in swagger and update the generated client.

fix(ui/dataLoaders): Update cur_swagger for type safety in generated client

---

mock/storage_reads.go
storage/reads/response_writer.go
storage/reads/response_writer_test.go

Follow-up to #1265
Return read/cursor statistics with streaming read requests.
Read/cursor statistics were not returned with `ResponseWriter.WriteResultSet`
Add the statistics to the gRPC stream trailer. This keeps the protobuf message simple, and the client gets one stats value in the end, rather than trying to keep track per frame or per batch of frames.

feat(storage): return cost stats with read response via gRPC trailer

---

.circleci/config.yml

See https://github.com/influxdata/platform/pull/1672 for background
Temporarily remove the call to make test-integration so that nightly
builds are not broken.
Related to https://github.com/influxdata/platform/issues/1676

remove make test-integration call from deploy

---

ui/src/shared/components/DygraphTransformation.tsx
ui/src/shared/parsing/flux/dygraph.ts

Properly handle queries without `_time`

---

ui/src/onboarding/containers/OnboardingWizard.tsx
ui/src/onboarding/containers/OnboardingWizardPage.tsx

Clicking a telegraf plugin in the sidebar now changes the url to reflect that sub step

Handle routing from onboarding sidebar

---

http/errors.go

Closes https://github.com/influxdata/platform/issues/1783
Due to some recent changes of the error embedding, the original http error encoding no longer create the correct response. This patch will fix that issue;

fix(http): fix the correct response

---

.circleci/config.yml

Update how CircleCI saves cached data. Since dependencies don't change often builds will reuse the same cache based on the checksum of go.sum. When dependencies update the checksum will change resulting in a new cache rebuild. This first rebuild will take a few seconds longer but all additional builds will speed up.
Additional discussion around this can be found in PR #1780.

chore(ci): Reset CircleCI cache logic

---

tsdb/tsm1/file_store.go

This commit adds the `.tss` files generated for TSM statistics to the `FileObserver` so that package users can be notified when new stats files are created and removed.
TSS files were not being notified for backup storage.
Add TSS files to the `FileObserver` calls.

Allow stats files to be observed for finishing/unlinking.

---

tsdb/index_test.go
tsdb/tsi1/cache.go
tsdb/tsi1/config.go
tsdb/tsi1/index.go

This PR allows the TSI cache (which caches bitsets of series IDs for key/value pairs) to have its size altered.
The cache size was fixed at 100.
Make it a configuration variable and increase the default size.

Allow TSI cache to be dynamically altered

---

cmd/influx_inspect/buildtsi/buildtsi.go
pkg/rhh/rhh.go
storage/engine.go
tsdb/series_file.go
tsdb/series_index.go
tsdb/series_partition.go
tsdb/tsi1/cache.go
tsdb/tsi1/index.go
tsdb/tsi1/partition.go

This PR allows metrics to be disabled.
For some tasks, such as running tooling online to build a live index, we don't want to integrate the engine metrics.
Allow the metrics to be disabled before opening the series file or index.

Allow metrics to be disabled

---

tsdb/tsm1/engine.go

Ensures there is a tracker available when a full compaction kicks in.

Fix nil tracker for full compactions

---

ui/mocks/dummyData.ts
ui/src/onboarding/reducers/dataLoaders.test.ts
ui/src/onboarding/reducers/dataLoaders.ts
ui/src/onboarding/utils/pluginConfigs.ts

Closes #1829
the wrong values were getting overwritten so nothing was actually changing in the stored configs when updating

Fix(ui/dataLoaders): Update config field modifiers

---

http/ready.go

This PR adds some extra detail about how long the process has been up to the `/ready` endpoint.
The contents of the response will now look like:
```json
{
"status": "ready",
"started": "2018-12-12T11:43:36.824427Z",
"up": "5.452864366s"
}
```

Add uptime to ready endpoint

---

tsdb/tsm1/engine.go

Added a compaction tracker to the full compaction strategy.
The tracker was only attached to leveled compaction strategies and caused a panic when the tracker was later invoked.
Add the tracker to the full compaction strategy as well.

Fix full compaction panic.

---

tsdb/tsi1/cache_test.go
tsdb/tsi1/log_file_test.go
tsdb/tsi1/partition_test.go

Report the total number of gets, puts, and deletes at the end of the
test. I've found this kind of output to be a useful sanity check in
similar tests that exercise concurrency involving tasks.
Use a local random source in each goroutine. I unscientifically
eyeballed that to increase total operations by 5-10%.
Also call t.Parallel in a few more tests that involve disk access. This
shaves 1-2 seconds off the full tsi1 test suite on my machine.

test(tsdb/tsi1): test series id cache delete concurrently

---

go.mod
go.sum
http/query_handler_test.go

The test used `AND` instead of `and` which is not valid syntax. It also
did not include packages and imports in the generated JSON from parsing
the flux query.

fix(http): update the query handler to use valid flux syntax

---

storage/reads/group_resultset.go
storage/reads/group_resultset_test.go

If there is no data for the given time range, the group cursor should return `nil`. For the `groupNoneSort` function, move the `n` counter inside the if condition, so that it returns `0` if no series have data.
Moves the check to determine if a series has data for the current time range into the `groupBySort` function, which is consistent with the `groupNoneSort` function and correctly returns `len(rows) == 0` when there are no group rows.
Closes influxdata/flux#319

Fix panic when read request results in empty an group

---

.circleci/config.yml

The docker container we're using has 2 vCPUs. -p=8 was working fine for
a while, but diagnosing #1832 looks like the tsi1.test process was
likely getting OOM-killed. Reducing from -p=8 to -p=4 ought to reduce
memory pressure enough to avoid OOM kills, hopefully.
Also remove a stale TODO.

ci: use -p=4 on circle

---

ui/src/onboarding/components/OnboardingSideBar.tsx
ui/src/onboarding/containers/OnboardingWizard.tsx
ui/src/onboarding/containers/OnboardingWizardPage.tsx

Closes #1916 
Clicking add new source would use the "go back" functionality rather than taking you to the streaming sources step
clicking go back takes you to the streaming sources step

Fix(ui/dataLoaders): Update streaming button to send you to the streaming step

---

ui/src/onboarding/components/OnboardingSideBar.test.tsx
ui/src/onboarding/components/OnboardingSideBar.tsx
ui/src/onboarding/components/__snapshots__/OnboardingSideBar.test.tsx.snap

Closes #1889 
The download button was visible, even if there was nothing to download
Dont show the download button if there's nothing to download

Fix(ui/dataLoaders): Hide download button if there's nothing to download

---

ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx
ui/src/shared/components/permissionsWidget/PermissionsWidget.scss
ui/src/shared/components/permissionsWidget/PermissionsWidget.tsx
ui/src/shared/components/permissionsWidget/PermissionsWidgetItem.tsx
ui/src/shared/components/permissionsWidget/PermissionsWidgetSection.tsx

Intended for use anywhere Chronograf allows a user to read or update permissions
**`Read` mode:**
**`Write` mode:**
```
import PermissionsWidget, {PermissionsWidgetMode, PermissionsWidgetSelection} from 'src/shared/components/permissionsWidget/PermissionsWidget'
```
If using **Read** mode:
```
<PermissionsWidget
mode={PermissionsWidgetMode.Read}
heightPixels={300}
>
<PermissionsWidget.Section id="apples" title="Apples">
<PermissionsWidget.Item
label="Pick from tree"
id="apples-pick"
selected={PermissionsWidgetSelection.Selected}
/>
<PermissionsWidget.Item
label="Eat"
id="apples-eat"
selected={PermissionsWidgetSelection.Selected}
/>
</PermissionsWidget.Section>
<PermissionsWidget.Section id="limes" title="Limes">
<PermissionsWidget.Item
label="Pick from tree"
id="limes-pick" …
```

Introduce Permissions Widget

---

storage/reads/table.gen.go
storage/reads/table.gen.go.tmpl

Expand the lock period for tables to protect against a changing underlying cursor. See included data race report for details.
<details>
<summary>Data race report</summary>
```
WARNING: DATA RACE
Write at 0x00c0002665d8 by goroutine 156:
github.com/influxdata/platform/storage/reads.(*floatMultiShardArrayCursor).reset()
/Users/benbjohnson/src/platform/storage/reads/array_cursor.gen.go:103 +0x83
github.com/influxdata/platform/storage/reads.(*multiShardArrayCursors).createCursor()
/Users/benbjohnson/src/platform/storage/reads/array_cursor.go:145 +0x63c
github.com/influxdata/platform/storage/reads.(*resultSet).Cursor()
/Users/benbjohnson/src/platform/storage/reads/resultset.go:61 +0x11a
github.com/influxdata/platform/storage/reads.(*tableIterator).handl …
```

fix(storage): Extend lock during stats fetch to prevent race

---

cmd/influxd/main.go
cmd/influxd/main_test.go

Closes #1414
This commit moves the `Main.cancel()` execution to the `main_test.go` file so it's only executed for tests. This was interfering with the shutdown process on the regular `influxd` binary. Related: https://github.com/influxdata/flux/pull/478
The `flux.Controller` shutdown too quickly and didn't wait for queries to finish. This caused a `SIGSEGV` because the storage would close immediately after and not wait for the queries.
Move the cancellation required by the integration test.

fix(cmd/influxd): Refactor test cancellation out of main path.

---

.circleci/config.yml

This change configures CircleCI to perform a nightly build,  `make nightly`.

chore(ci): Setup nightly build

---

tsdb/tsm1/reader.go
tsdb/tsm1/reader_test.go
tsdb/tsm1/writer.go

`DeleteRange` would start at the first key in the index and do a linear walk until it reached the first key to be deleted. This is obviously bad when attempting to delete a large key. Instead, do a seek to the first key to be deleted.
I did very short benchmarks, so lots of noise, but:
```
BenchmarkIndirectIndex_DeleteRangeLast-8     310663434       1550          -100.00%
BenchmarkIndirectIndex_DeleteRangeFull-8     18776033480     773649708     -95.88%
```
`DeleteRangeFull` is the closest thing to what retention does right now.

tsm1: tombstone performance

---

README.md

Updated readme to contain information on installing bazaar if seeing `error loading module requirements` error on make.

Add information about bazaar to readme file

---

.circleci/config.yml

https://circleci.com/gh/zhulongcheng/platform/137?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
#!/bin/sh -eo pipefail
false
Exited with code 1
```

fix(ci): add required jobs

---

ui/src/authorizations/apis/index.ts
ui/src/me/components/account/TokenRow.tsx
ui/src/me/components/account/Tokens.tsx
ui/src/me/components/account/TokensList.tsx
ui/src/me/components/account/__snapshots__/Account.test.tsx.snap
ui/src/shared/copy/notifications.ts

Closes #1427
Adds a delete button to the `TokenRow` component that allows the user to delete a token. This works by optimistically removing the token from the state of the `TokensList` component, and then making a call to remove it from the backend. The user will be notified if the deletion was successful or unsuccessful.

Add delete button to token index row

---

bucket.go
http/bucket_service.go
http/bucket_test.go
http/paging.go
http/piging_test.go
http/swagger.yml
mock/paging.go
paging.go

https://github.com/influxdata/platform/blob/master/http/swagger.yml#L3809-L3827
https://github.com/influxdata/platform/blob/master/http/bucket_service.go#L207-L213
https://github.com/influxdata/platform/blob/master/http/auth_service.go#L66-L72
Paging has been defined in swagger, but it is not implemented in http server.
Try to add an implementation:
1. Add `PagingLinks`
```
// PagingLinks represents paging links.
type PagingLinks struct {
Prev string `json:"prev,omitempty"`
Self string `json:"self"`
Next string `json:"next,omitempty"`
}
```
2. Add `PagingFilter` interface
```
// PagingFilter represents a filter containing url query params.
type PagingFilter interface {
// QueryParams converts `[Resource]Filter` fields to query params. …
```

feat(http/paging): add paging implementation

---

errors.go
errors_test.go

Closes https://github.com/influxdata/platform/issues/1863
after this pr. 
previous json with embedded error will be changed from
```
{"code":"not found","msg":"organization not found","op":"inmem/FindBuckets","err":"{\"code\":\"\",\"err\":\"{\\\"code\\\":\\\"\\\",\\\"op\\\":\\\"inmem/FindOrganization\\\",\\\"err\\\":\\\"{\\\\\\\"code\\\\\\\":\\\\\\\"not found\\\\\\\",\\\\\\\"msg\\\\\\\":\\\\\\\"organization not found\\\\\\\",\\\\\\\"op\\\\\\\":\\\\\\\"inmem/FindOrganizations\\\\\\\"}\\\"}\"}"
``` 
to
```
{"code":"not found","msg":"organization not found","op":"inmem/FindBuckets","err":{"code":"","err":{"code":"","op":"inmem/FindOrganization","err":{"code":"not found","msg":"organization not found","op":"inmem/FindOrganizations"}}}
```

fix(platform): use json struct instead of string for embed error

---

ui/src/onboarding/components/configureStep/lineProtocol/PrecisionDropdown.tsx
ui/src/onboarding/reducers/dataLoaders.ts
ui/src/types/v2/dataLoaders.ts

Closes #1962 
Remove U as precision option, 
Make nanosecond the default selection, 
Put precisions in order of magnitude.

Line protocol precision polish

---

http/api_handler.go
http/cur_swagger.yml
http/query.go
http/query_handler.go
http/swagger.yml

Backend Portion of #1530
Wasn't able to analyze query request without actually executing the query.
Add an analyze endpoint that returns friendly json like
```json
{
"errors": [
{
"line": 11,
"column": 41,
"character": 674,
"message": "rule StringLiteral: string literal not terminated"
},
{
"line": 11,
"column": 48,
"character": 681,
"message": "rule ArrayElements: interface conversion: string is not ast.Expression: missing method Copy"
}
]
}
```

add /query/analyze endpoint query http handler

---

http/cur_swagger.yml
ui/mocks/dummyData.ts
ui/src/api/api.ts
ui/src/authorizations/apis/index.ts
ui/src/onboarding/apis/index.ts

The response from the get/authorizations endpoint was recently changed from having an array called `auths` to one called `authorizations`. This PR changes the generated client as well as the parsing of the response from this endpoint.

Match shape of get/authorizations to backend response

---

bolt/bbolt_test.go
bolt/kv.go
bolt/kv_test.go
bolt/user_test.go
go.mod
go.sum
inmem/kv.go
inmem/kv_test.go
kv/cursor.go
kv/cursor_test.go
kv/example.go
kv/store.go
testing/kv.go
user.go

This PR is a spike intended to be a proof of concept before we go on to adapt other services.
This PR introduces a new directory `kv` that contains an interface for a generic key value store. The intention is that all of the services to be implemented in this package. This way we can have a single location where the service implementations live and we have those implementations backed by anything that implements the `kv.Store` interface.
The interface as it is now should closely resemble the boltdb/stm style. It is likely that this interface may need to change a bit to allow for other implementations.
My intention is to have this be a place where we can discuss the design decisions and work on a suitable interface for us to build off of.

WIP: Spike for generic key value store

---

ui/src/onboarding/reducers/dataLoaders.test.ts
ui/src/onboarding/reducers/dataLoaders.ts

Closes #1974
Update addTelegrafPlugin action to sort TelegrafPlugins with asc name when plugin bundles are added.

Telegraf plugins alphabetized in the sidebar

---

ui/src/onboarding/components/verifyStep/ConnectionInformation.test.tsx
ui/src/onboarding/components/verifyStep/ConnectionInformation.tsx
ui/src/onboarding/components/verifyStep/DataListening.tsx
ui/src/onboarding/components/verifyStep/DataStreaming.tsx
ui/src/onboarding/components/verifyStep/VerifyDataStep.tsx
ui/src/onboarding/components/verifyStep/VerifyDataSwitcher.tsx
ui/src/onboarding/components/verifyStep/__snapshots__/ConnectionInformation.test.tsx.snap

Closes #1972 
Error state and data not found state both displayed connection not found in the connection information.
Now error state shows error while listening for data and none found shows No data found
Additionally, removed an extra fetch for authtoken. since this is being done higher up in the tree, it doesnt need to be done again.

fix(ui/dataLoaders): Separate the error state from the data not found

---

ui/src/onboarding/components/OnboardingSideBar.tsx
ui/src/onboarding/reducers/dataLoaders.test.ts
ui/src/onboarding/reducers/dataLoaders.ts
ui/src/types/v2/dataLoaders.ts

Closes #1971
Previously, the symbol for a plugin config was an open circle whether the user had not yet set any fields on it or if the fields were invalid.
The circle will now be the default symbol when a user has not yet modified a plugin configuration. If the plugin configuration is modified and is invalid, a red x will be shown instead.

Display red x in sidebar when plugin config is invalid

---

errors.go

Rename "msg" field to "message" for Error json

---

bolt/telegraf.go
telegraf.go
telegraf/plugins/type.go
telegraf_test.go
testing/telegraf.go

Closes https://github.com/influxdata/platform/issues/1903
_What was the problem?
previous implementation a map of pointer, won't allocate a new pointer.
use reflect.New to always allocate a new pointer when doing interface Unmarshalling.
added more testing
fixed bugs in old testing

fix(platform): fix the pointer alloc for telegraf config

---

http/auth_service.go
http/authentication_middleware.go
http/bucket_service.go
http/dashboard_service.go
http/errors.go
http/handler.go
http/label_service.go
http/macro_service.go
http/onboarding.go
http/org_service.go
http/query_handler.go
http/scraper_service.go
http/server.go
http/source_service.go
http/task_service.go
http/telegraf.go
http/usage_service.go
http/view_service.go

Closes #1904 
Closes #1602
This PR removes potential second calls to `w.WriteHeader` and replaces it with a log that there was an error during encoding.
1. There were places where explicit multiple calls to w.WriteHeader. Those were removed.
2. Loggers were added to each handler that encoded responses and log lines were added instead.
3. Notes where other potential calls to w.WriteHeader were added.

remove multiple calls to w.WriteHeader in http handlers

---

http/api_handler.go
http/swagger.yml

Closes #1873 
The swagger for the top level links had become out of sync with what the api handler returned.
I alphabetized both the links in the code and in the swagger doc so that future additions are easier to make and verify.

Update swagger doc for /api/v2/ response

---

bolt/onboarding.go
http/swagger.yml
inmem/onboarding.go
testing/onboarding.go

Closes #1861 
This PR renames the onboarding token description to be `<user name>'s` and adds the token description to swagger.

Make onboarding token description "<users name>'s token"

---

.goreleaser.yml
Makefile

goreleaser must run make generate before compiling influxd. This will generate the required files for chronograf to be included.
Closes #2050

chore(ci): Run make generate

---

http/health.go
http/health_test.go
http/swagger.yml

Closes #2021 
Update /health endpoint to give the most basic answer possible.
Health endpoint was sending back "healthy" whereas swagger check is now "pass" and "fail."
Update and add the test.

fix(http): health endpoint now returns pass

---

http/task_service.go
task/platform_adapter.go

1. The `pAdapter` did not have a `RunController`.
2. The `task_service` memberHandlers doesn't work and the `url missing member id` error is produce.
1. Pass the `RunController` to the `pAdapter`.
2. Changing the mapping from a `tid` to a `id` according to implementation of [decodeDeleteMemberRequest](https://github.com/influxdata/platform/blob/b2afb98f7c2d4dfbce12757c0beb37705e585223/http/user_resource_mapping_service.go#L206).

Fixed the task id path, Added RunController instance to pAdapter

---

http/task_service_test.go

Fixes merge issue from #1562 
Update tests to sync with the router parameters.
Tests used :tid while the routes used :id
Update the tests to use 🆔

fix(http): update task test to use :id

---

http/requests.go
http/requests_test.go
http/swagger.yml

Closes #2106 
We should use `org` and `orgID` rather than `organization` and `organizationID` as HTTP query parameters to `/api/v2/query`
Documentation in swagger had `org`.
Update docs and add tests to show org/organizationID,

fix(http): change /query to use org/orgID

---

http/swagger.yml
models/points.go
models/points_test.go

Closes #1959 
1. Use SI symbols `us` and `ns` rather than `u` and `n` for timestamp precision.
2. Remove `h` (hours) and `m` (minutes) from timestamp precision.
I don't think we need hours and minutes since the Unix epoch.
We didn't have a consistent unit system for precision.
_What was the solution?
Use only `ns`, `us`, `ms`, and `s` of precision since the Unix epoch for timestamps.

feat(models): only use common SI time units for timestamp precision

---

.circleci/config.yml

Update CircleCI trigger time to allow for a new nightly to be built at 10:00 pm UTC.

chore(ci): Update trigger schedule

---

go.mod
go.sum
http/telegraf.go
http/telegraf_test.go
mock/telegraf_service.go

Closes #1587 
Add fuzzy matching of Accept header to GET /api/v2/telegrafs/:id.
Accept header parsing is a much deeper topic than simply comparing strings.
See https://tools.ietf.org/html/rfc7231#section-5.3.2
Use a library that handles most of the Accept header RFC.  Also, added tests for GET of /api/v2/telegrafs and /api/v2/telegraf

feat(http): add accept parsing for telegraf

---

bolt/kv_test.go
inmem/kv_test.go
inmem/user_service.go
kv/example.go
testing/user_service.go
testing/util.go

Related #2072
inmem user service's FindUser would only check for name, but not ID.
I've added a few more tests filter permutations and then fixed the resulting bugs.

fix(inmem): user service now filters by id

---

ui/src/shared/utils/view.ts

Tables currently crash when time axis is horizontal- also time axis should be vertical by default.

Set default time axis to vertical

---

http/query.go
http/query_handler.go
http/query_test.go

Closes #1918 
This PR allows users to submit `GET /api/v2/query` requests where the flux query is provided via query param called `query`.

Add support for get /api/v2/query

---

ui/src/tasks/actions/v2/index.ts

There has been a change to the structure of errors coming back from the server, `x-influx-error` is no longer a field on the response header, and notifications were failing because FE was expecting previous format.

Fix error notifications on tasks

---

tsdb/tsm1/tombstone.go
tsdb/tsm1/tombstone_test.go

Closes #1833.
This PR adds support for prefix-based tombstone keys, along with a new API to creating them. Prefix keys are to be used when the intention is to delete all series keys matching a prefix, which commonly might be an organisation or an oganisaton+bucket combination.
In these cases we can use a single prefix key rather than adding a tombstone entry for each and every matching key.
The existing `tsm1` engine does not provide support for prefix base tombstone keys.
For the `v4` tombstone version we use a `32 bit` value to represent the length of a tombstone entry's key. We don't need that many bits, so we reduce it to 24 bits. This leaves us with 8 spare bits when encoding a tombstone entry. …

Add support for prefix tombstone entries

---

ui/src/shared/constants/fluxFunctions.ts

Closes #2115 
Updated from function example in constants to 'bucket_name' instead of 'telegraf/autogen'

Update from function example to bucket_name instead of telegraf/autogen

---

ui/src/shared/components/tables/TableGraphs.tsx
ui/src/shared/utils/filterTables.ts
ui/src/shared/utils/view.ts

Closes #2097 
Extracts and updates field options for a table graph view. Currently, only the default `_time` field option was being displayed.

feat(ui): add field options to view

---

ui/src/organizations/components/MemberList.tsx
ui/src/organizations/components/Members.tsx
ui/src/organizations/dummyData.ts

Closes #1378 
Created dummy data for members since there is no data in db for members. Added the filter box on the header of members tab and implemented the functionality to update state when user enters text

Create dummy data for members and add filter box to the header

---

write/batcher.go
write/batcher_test.go

In the case that there is a read error, we would close the lines
channel before sending the error into the read error channel. closing
lines then allows the write goroutine to possibly send in a nil error
before read is able to, causing the main function driving both to
return a nil error. Additionally, it is possible for both reads and
writes to race sending errors into their channels, and the main
goroutine will only read from one, causing the other goroutine to leak.
To fix this, we close lines only after we have sent an error into
the channel, we ensure we read from both errors to make sure that
both have exited, and we unify the channels and add a buffer of size
two to the channel. It is possible for write to exit leaving read blocked
forever, but write only exits with a nil error …

fix(write): fix close logic to avoid race from read error

---

ui/src/onboarding/components/selectionStep/SelectDataSourceStep.tsx

Previously, if you refreshed on the streaming onboarding step, the url would still be that of the streaming step but would show the data loaders type selection rather than the streaming selection. this changed made it so that if the url has the substep of streaming, then the type should be set to streaming.

fix(ui/dataLoaders): Ensure type is streaming if the substep is streaming

---

ui/mocks/dummyData.ts
ui/src/onboarding/constants/pluginConfigs.ts
ui/src/onboarding/reducers/dataLoaders.test.ts
ui/src/onboarding/utils/__snapshots__/pluginConfigs.test.ts.snap
ui/src/onboarding/utils/pluginConfigs.test.ts
ui/src/types/v2/dataLoaders.ts

Closes #1894
Removed the plugin bundles from plugin configs and updated the tests to match correct bundles and names.

Remove plugin bundles that don't match the protoboards

---

cmd/influx_inspect/buildtsi/buildtsi.go
tsdb/tsm1/compact_test.go
tsdb/tsm1/engine.go
tsdb/tsm1/file_store.go
tsdb/tsm1/file_store_key_iterator.go
tsdb/tsm1/file_store_key_iterator_test.go
tsdb/tsm1/reader.go
tsdb/tsm1/reader_block_iterator.go
tsdb/tsm1/reader_index_iterator.go
tsdb/tsm1/reader_offsets.go
tsdb/tsm1/reader_offsets_test.go
tsdb/tsm1/reader_test.go

TL;DR:
- Fixes #1983 
- Improves benchmarks and reduces page faults
- Each commit is self contained for review if desired
---
This uses a `[]uint32` instead of a `[]byte` stored off the Go heap.
Consolidates offsets from `int`, `int32`, `uint32` into just `uint32`.
Rather than look up tombstones by `[]byte`, look them up by the `uint32` offset that almost certainly have access to already.
DeleteRange wasn't precise about keys being deleted, had incorrect locking, and didn't seek when the next key to delete wasn't the next key in the index.
Estimates page faults by keeping track of the most recently accessed page, and considers it a fault if the accessed page is not the most recently accessed, or the one after it.
Reduces the amount of page faults by ~30% at very little memory overhead. …

tsm1 index fixes and improvements

---

.goreleaser.yml

We don't currently plan to provide 32 bit support in Platform. As such, we don't want to attempt to build binaries targetting 32 bit architectures. 
This PR removes support for building 32bit architectures, including i386, arm6 and arm7.
Closes #2233.

Remove 32bit architectures from builds

---

ui/src/clockface/components/wizard/ProgressBar.scss
ui/src/clockface/components/wizard/ProgressBar.tsx
ui/src/onboarding/containers/OnboardingWizard.tsx

Closes #1939
The admin step of the onboarding wizard should not be able to be skipped. However, it is skippable by clicking on the steps in the progress bar. this pr adds a check in the progress bar that prevent non skippable steps from being skipped via the progress bar

fix(ui/onboarding): Prevent unskippable steps from being skipped with progress bar

---

ui/src/clockface/components/overlays/OverlayContainer.tsx
ui/src/me/components/account/Tokens.tsx
ui/src/me/components/account/TokensList.tsx
ui/src/me/components/account/ViewTokenOverlay.tsx
ui/src/me/components/account/__snapshots__/ViewTokenOverlay.test.tsx.snap
ui/src/onboarding/OnboardingWizard.scss
ui/src/onboarding/components/verifyStep/TelegrafInstructions.tsx
ui/src/onboarding/components/verifyStep/__snapshots__/TelegrafInstructions.test.tsx.snap
ui/src/shared/components/CopyText.scss
ui/src/shared/components/CopyText.tsx
ui/src/style/chronograf.scss

Closes #2285
Extracted copy to clipboard button from onboarding to it's separate component which takes in token or any snippet to be copied. CopyToken component also takes in notify prop to show notification that the text was copied.

Display token on my account token overlay

---

telegraf.go
ui/src/onboarding/constants/pluginConfigs.ts

In the check for a valid plugin, procstat should be singular.
additionally, exe is required in the front end object.

Change typo of procstats to procstat and make exe required

---

bolt/dashboard.go
cmd/influxd/launcher/launcher.go
cmd/influxd/launcher/launcher_test.go
dashboard.go
fs/proto.go
fs/proto_test.go
http/api_handler.go
http/dashboard_service.go
http/proto.go
http/proto_test.go
http/swagger.yml
mock/proto.go
proto.go

Closes #1877 
This PR introduces `protos` (the extension of the idea of protoboards, templated dashboards, from chronograf).
Specifically the following were introduced
* Proto API endpoints
- `GET  /api/v2/protos`
- `POST /api/v2/protos/:protoID/dashboards`
* a `protos-path` was added to the `influxd` command
- it is expected that all required protos should be added to this directory in the structure described below
```json
{
"id": "0000000000000001",
"name": "system",
"dashboards": [
{
"dashboard": {
"name": "hello",
"description": "oh hello there!",
"cells": [
{
"id": "da7aba5e5d81e550",
"x": 1,
"y": 2,
"w": 3,
"h": 4
}
]
},
"views": {
"15743100361885476176": {
"name": "hello",
"properties": {
"shape": "chronograf-v2",
"queries": null,
"axes": …
```

Add protos (templates of dasboards)

---

cmd/influx/setup.go

Closes https://github.com/influxdata/platform/issues/2284
During onboarding, Instead of print Token with tab writer, print in a separate line. 
`
Your token has writen in /Users/kwang/.influxdbv2/credentials
`

fix(cmd/influx): don't print token, print the file where it stored

---

cmd/influxd/launcher/launcher.go
cmd/influxd/launcher/launcher_test.go
cmd/influxd/main.go
storage/bucket_service.go
storage/bucket_service_test.go
storage/engine.go
storage/retention.go
testing/kv.go

Partially completes #1837.
This PR connects the API-level bucket service with the storage engine, by wrapping the bucket service implementation with a storage-backed one.
When deleting a bucket via the API, the storage engine will now attempt to delete all the data associated with that bucket.
In order for this to work fully #1836 will need to be completed.
However, it's safe to merge this now, the storage engine portion of deleting a bucket will simply be a no-op for the moment. An new end-to-end test is currently skipped, and this should be unskipped when #1836 lands. /cc @zeebo

Wire up Storage Engine to API-layer BucketService

---

auth.go
authz.go
authz_test.go
bolt/onboarding.go
bolt/onboarding_test.go
inmem/onboarding.go
session.go
task/validator.go
testing/onboarding.go
user_resource_mapping.go

Closes #2252 
As https://github.com/influxdata/platform/pull/2157 introduced a new structure for permissions, we now need to grant org level permissions for organization owned resources. Specifically, we introduces permissions for dashboards, tasks, sources, buckets, telegrafs, and users for organizations. The permission for these resources now contains an `ID` that links to the organization.
**Note:** We still need a way to describe the write/read actions for an individual task. This may imply the need to add an `OrganizationID *ID` to the permissions struct.
@mark-rushakoff @lyondhill thoughts on the note above.

Add org admin and member specific permissions

---

cmd/influxd/launcher/launcher_test.go
storage/engine.go
tsdb/tsm1/engine_delete_prefix.go

Closes #1837
Hooks up the engine's DeleteBucket call to delete a prefix out of the tsm1 engine, fixes a couple of bugs found during the integration, and enables the test that it works.

Hook up DeleteBucket to the tsm1 engine
