Gopkg.lock, auth.go, bolt/authorization.go, bolt/authorization_test.go, bolt/bbolt.go, bolt/bucket.go, bolt/bucket_test.go, bolt/organization.go, bolt/organization_test.go, bolt/user.go, bolt/user_test.go, bucket.go, cmd/idp/authorization.go, cmd/idp/bucket.go, cmd/idp/ifql.go, cmd/idp/internal/tabwriter.go, cmd/idp/main.go, cmd/idp/organization.go, cmd/idp/user.go, cmd/idpd/main.go, http/auth_service.go, http/bucket_service.go, http/org_service.go, http/user_service.go, prometheus/auth_service.go, testing/auth.go, testing/bucket_service.go, testing/organization_service.go, zap/auth_service.go
Additionally, I've added IDs to `authorizations` so that we can refer to them without having to refer to the token string.
=> Add bolt implementation of organzation/user/authorization services

query/functions/from_csv.go
extended fromCSV to have an optional file:  parameter so that larger blocks of text can be given by filename instead of a blob of text
=> feat(cmd/ifqld): fromCSV reads files now

Gopkg.lock, query/functions/to_http.go, query/functions/to_http_test.go
toHTTP function moved from github.com/influxdata/ifql
https://github.com/influxdata/ifql/pull/362
=> toHTTP function moved from github.com/influxdata/ifql

query/functions/to_http.go, query/functions/to_http_test.go
I forgot to rename addr to url (as @pauldix asked for) as part of the last PR.
Woops.
Here it is.
=> addr -> url

cmd/transpilerd/main.go, http/server.go
Introduce logging into the http server implementation for when the
server is shutting down and reporting when we receive a signal for a
hard shutdown.
=> feat(cmd/transpilerd): follow the logging style guide for transpilerd

query/execute/format.go
Now columns are ordered the same as the partition key.
=> fix(query/execute): Update formatted sort order of cols

cmd/transpilerd/main.go, http/transpiler_handler.go
The /query endpoint didn't have an orgID parameter so we can't have one
in the transpiler endpoint. This removes the parameter and replaces it
with a command line parameter that sets which organization we are using
for querying ifql.
Related to #65.
=> fix(http): remove the orgID parameter from the transpiler handler

query/functions/limit.go, query/functions/limit_test.go
=> feat(query/functions/limit): Add offset to limit functions

query/csv/result.go
An EOF should not be reported as an error but as an indication that no
more data is available.
=> fix(query/csv): Fix EOF causing error

cmd/transpilerd/main.go
This removes the `--org` parameter because we can't properly decode the
name into an organization id without access to the idp daemon. We will
either have to open access to that or not have that feature.
=> fix(cmd/transpilerd): fix transpilerd to use only --org-id

bolt/bbolt.go, bolt/dashboard.go, bolt/dashboard_test.go, cmd/idpd/main.go, dashboard.go, dashboard_test.go, http/dashboard_service.go, http/platform_handler.go, testing/dashboards.go
This PR introduces a dashboard service with associated boltdb implementation.
=> Add dashboard service

context/token.go, http/platform_handler.go, http/token_parse_test.go, http/token_parser.go
Moved from 
https://github.com/influxdata/idpe/pull/558
https://github.com/influxdata/idpe/issues/550
I will create another PR in idpe, once this merged
=> fix(http): fix auth header

query/influxql/README.md
Update the transpiler docs to account for a change in the query
language. A slightly different method is now used with some
clarifications previously existing problems.
The readme is also indexed with a table of contents for easier reading.
=> docs(query/influxql): update the transpiler readme

Gopkg.lock, query/functions/to_kafka.go, query/functions/to_kafka_test.go
a toKafka function that is compatible with what telegraph wants to read from kafka.
=> a toKafka function

query/influxql/cursor.go, query/influxql/group.go, query/influxql/transpiler.go, query/influxql/transpiler_test.go
=> feat(query/influxql): implement filter conditions for tags in the transpiler

query/influxql/transpiler.go, query/influxql/transpiler_test.go
=> feat(query/influxql): support multiple select statements

query/influxql/transpiler_test.go
One of the transpiler unit tests got messed up during a recent PR. This
restores the unit test for conditionals.
=> fix(query/influxql): messed up a transpiler unit test

Gopkg.lock
=> dep: update yarpc dependency

http/org_service.go
=> prevent creation of nameless organizations

query/compile.go, query/compiler/runtime.go, query/execute/row_fn.go, query/functions/to_http.go, query/functions/to_kafka.go, query/functions/typeconv.go, query/functions/yield.go, query/interpreter/interpreter.go, query/interpreter/interpreter_test.go, query/repl/repl.go, query/values/array.go, query/values/object.go, query/values/values.go
evaluate CallExpression to determine if function has side effects
return all side effects
add Equal method to Value interface
=> Evaluate semantic graph and return results of side effects

query/control/controller.go
=> fix(query/control): discard finished queries from the priority queue

query/control/controller.go
=> fix(query/control): race condition when attempting to plan a query in the controller

query/functions/testdata/group_by_field.flux, query/functions/testdata/group_by_field.in.csv, query/functions/testdata/group_by_field.out.csv
Addresses #301; Adds a test which explicitly groups by a field, in this case, `_value`.
=> Add flux test for explicitly grouping by field

dbrp_mapping.go, testing/dbrp_mapping.go
Also renames DBRPMapper to DBRPMapping to keep names consistent.
=> chore: Add testing helpers for DBRPMapping

http/query_service.go
This makes it so we can encode errors in HTTP headers so long as the
encoder did not write anything.
This also changes the behavior to encode the stats trailer even in the
event of an error.
=> fix: Defer writing HTTP headers in query service

.circleci/config.yml, .goreleaser.yml, Makefile, docker/flux/Dockerfile, docker/flux/entrypoint.sh
=> feat(docker): create a fluxd nightly docker image

kit/signals/context.go, kit/signals/context_test.go
Signed-off-by: Lorenzo Fontana <lo@linux.com>
=> chore(kit/signals): removed duplicated check for signals and add an example

id.go, id_test.go
Signed-off-by: Lorenzo Fontana <lo@linux.com>
Co-authored-by: Chris Goller <goller@gmail.com>
=> Static id from string function

mock/generators.go, testing/auth.go, testing/bucket_service.go, testing/dashboards.go, testing/organization_service.go, testing/user_service.go, testing/util.go
Related to #443 
Signed-off-by: Lorenzo Fontana <lo@linux.com>
=> Testing using ids generated from string using Decode

query/docs/SPEC.md
=> update flux grammar spec to include OptionStatement

Gopkg.lock, Gopkg.toml
Reverts influxdata/platform#493
=> Revert "Use platform branch on influxDB"

chronograf/ui/src/admin/components/chronograf/OrganizationsTableRow.tsx, chronograf/ui/src/admin/containers/chronograf/AllUsersPage.tsx, chronograf/ui/src/sources/components/SourceForm.tsx, chronograf/ui/src/types/auth.ts, chronograf/ui/src/types/index.ts, ui/src/side_nav/components/OrgLink.tsx, ui/src/side_nav/components/UserNavBlock.tsx
Cherry Picked from chronograf.
=> Bugfix/no org name (#4014)

task/backend/bolt/bolt.go, task/backend/inmem_store.go, task/backend/store.go, task/backend/storetest/storetest.go
Tasks for entire users and orgs were not deletable in the tasks backend
Make a method for deleting users and one for deleting orgs in the backend.Store interface
=> Delete users and orgs

cmd/fluxd/main.go, http/handler.go, http/status.go
Adds optional http logging to handler
No visibility into queryd requests
Add http logging to fluxd via a generic HTTP handler
=> feat: Add optional http logging to handler

task/backend/inmem_logreaderwriter.go, task/backend/scheduler.go, task/backend/scheduler_test.go, task/backend/store.go, task/backend/storetest/logstoretest.go, task/mock/scheduler.go
Preperatory change that should enable us to build more complex log writers.
change the log writer interface to include more then just the task id
The log writer interface didn't provide enough information to allow us to write task data back into the system bucket
=> feat(task): update the scheduler and logwriter interface

query/README.md
For details, the user can always look at the spec, but a good getting
started guide that works is needed.
At the moment, this does not use the influx command. It does include
instructions for how to get started with docker since that is easiest to
setup and use.
Fixes #509.
=> docs(query): modify the flux readme to turn it into a getting started instead

cmd/idpd/main.go, http/platform_handler.go, task/backend/coordinator/coordinator.go, task/backend/coordinator/coordinator_test.go, task/backend/store.go
We need a coordination layer to facilitate the communication in the api to the task service.
The api was also not connected in main to the http service.
=> feat(task): connect the api to tasks

task/backend/executor/executor.go, task/backend/executor/executor_test.go
By switching to passing a spec it allows us more control
=> refactor(task): set now on every execution

task/backend/bolt/bolt.go, task/backend/inmem_store.go, task/backend/store.go, task/backend/storetest/storetest.go
=> task name modification and uniqueness

query/control/controller.go
This documents the responsibilities of what the Controller does and is
expected to do. It describes some behaviors that aren't implemented, but
acts as a guide for what the Controller should do as we continue
developing the query engine and improving the internal mechanics.
Fixes #453.
=> docs(query/control): document the query/control package

query/control/controller.go, query/control/controller_test.go
=> fix(query/control): fix controller metrics

http/swagger.yml, task.go, task/backend/bolt/bolt.go, task/backend/executor/executor.go, task/backend/executor/executor_test.go, task/backend/inmem_logreaderwriter.go, task/backend/inmem_store.go, task/backend/scheduler.go, task/backend/store.go, task/backend/storetest/logstoretest.go, task/mock/scheduler.go
=> Update run schema

zap/tracer.go
By using a single header it is now easier and safer to manually inject a trace ID for debugging.
Use an HTTP header like so: 
```
Zap-Trace-Span: {"trace_id":"0261c39e5e9d4042","span_id":"0261c39e5e9d4043"}
```
to inject a manual root span for the request.
=> fix: Use a single HTTP header for zap trace context

query/execute/executor_test.go
=> fix: Fixes #697 data race in execute test

query/compile.go
=> fix: Fixes panic in query from sharing builtin decls

query/logging.go
The query statistics would only be read after the cancel call so we need
to wait for that before attempting to read the statistics rather than
attempting to read them immediately after the result is returned (before
it is read).
=> fix(query): report query statistics correctly

query/compile.go, query/functions/doc.go, query/operation.go
Closes #667 
Done with op-spec portion.  will be good to check progress to make sure it's going in the right direction. 
=> [WIP] query/functions/doc.go

http/swagger.yml
Closes #746 
Remove the extra path
A small piece of swagger was left behind during a refactor
Nuke the line
=> fix(http): remove swagger typos

.gitignore, Makefile, cmd/influxd/main.go, source/query.go
Closes #
Rename idpd to influxd
What's idpd?
influxd
=> chore(cmd/influxd): rename idpd to influxd

query/docs/SPEC.md, query/functions/histogram.go, query/functions/histogram_quantile.go, query/functions/histogram_test.go, query/interpreter/interpreter.go
=> feat: Add histogram function for computing bucket based histograms

query/docs/SPEC.md
Closes #510 
This commit specifies how packages, namespaces, and imports work in Flux
Flux currently doesn't have a notion of packages or a way to import external Flux source code.
Propose a design for packages and namespaces as well as the behavior of package imports.
=> spec outlining packages, namespaces, and imports

Gopkg.lock
=> Update influxdata/influxdb:platform vendor dependency

http/influxdb/source_proxy_query_service.go
Closes #680
This  PR encodes the JSON response from a 1x influxdb source into 2x style csv.
=> Add csv dialect support to 1x json response

snowflake/id.go, snowflake/id_test.go
This is for when you want a non-random machine ID from snowflake.
I also added some comments.
=> With machine ID

http/bucket_service.go, http/bucket_test.go, mock/bucket_service.go
Closes #794
This PR adds links to the bucket responses and tests those results.
=> feat(http): add links to bucket service response structures

http/swagger.yml
This PR adds documentation for 
* removed ping endpoint documentation
* added universal org query paramter
* added nested organization users route
* added links to response structures
* added macros (template variable) api
* updated queries endpoint
Not all things documented have been implemented.
=> Fill out swagger documentation to be the expected state of the API

http/org_service.go, http/swagger.yml
Fixed #795
Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>
=> Add links to orgs http handler

http/bucket_service.go, http/bucket_test.go
Fixed #790
Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>
=> Add org as a query param to bucket

query/influxql/README.md
Related to influxdata/flux#14.
=> feat(query/influxql): update the spec for time normalization in selectors

query/influxql/README.md, query/influxql/transpiler.go
=> README + initial skeleton in place

Jenkinsfile
This adds an api comparability test for platform.
=> Api compat test

snowflake/id.go, snowflake/id_test.go
...Woops
also added some tests.
=> fix panic in global id

query/influxql/errors.go, query/influxql/spectests/show_tag_values.go, query/influxql/spectests/show_tag_values_in_list.go, query/influxql/spectests/show_tag_values_multiple_measurements.go, query/influxql/spectests/testing.go, query/influxql/transpiler.go
=> feat: implement basic show tag values in the transpiler

chronograf/ui/src/dashboards/containers/DashboardPage.tsx, chronograf/ui/src/page_layout/PageLayout.scss, chronograf/ui/src/page_layout/components/Nav.scss, chronograf/ui/src/page_layout/components/Page.scss
When viewport is `< 800px` wide:
Otherwise:
=> Responsive Navigation

task/backend/inmem_logreaderwriter.go, task/backend/meta.go, task/backend/scheduler.go, task/backend/store.go, task/backend/storetest/logstoretest.go
This is the platform part of adding requestedAt to the task run log.
closes #753
=> add requestedAt to task log

chronograf/ui/src/clockface/components/Button/index.tsx, chronograf/ui/src/clockface/components/component_spacer/ComponentSpacer.scss, chronograf/ui/src/clockface/components/component_spacer/ComponentSpacer.tsx, chronograf/ui/src/clockface/index.ts, chronograf/ui/src/clockface/styles.scss, chronograf/ui/src/clockface/types/index.ts, chronograf/ui/src/dashboards/components/DashboardDefaultToggle.tsx, chronograf/ui/src/dashboards/components/DashboardsPageContents.tsx, chronograf/ui/src/dashboards/components/DashboardsTable.tsx, chronograf/ui/src/shared/components/index_views/IndexList.scss, chronograf/ui/src/shared/components/index_views/IndexList.tsx, chronograf/ui/src/shared/components/index_views/IndexListHeader.tsx, chronograf/ui/src/shared/components/index_views/IndexListRow.tsx, chronograf/ui/src/shared/components/index_views/IndexListTypes.ts, chronograf/ui/src/shared/components/index_views/README.md, chronograf/ui/src/shared/components/index_views/test/IndexList.test.tsx, chronograf/ui/src/shared/components/index_views/test/__snapshots__/IndexList.test.tsx.snap, chronograf/ui/src/style/_variables.scss, chronograf/ui/src/style/chronograf.scss
These components are purely presentational and intended for use in index view pages (such as Dashboards index)
There are two types of index views:
1. Index List
2. Index Grid (Coming soon)
`IndexList` is essentially a configurable table.
Import the component and associated types:
```
import {Alignment} from 'src/clockface'
import {
IndexListColumn,
IndexListRow,
} from 'src/shared/components/index_views/IndexListTypes'
import IndexList from 'src/shared/components/index_views/IndexList'
```
First define the columns present in your table. Each column has a few options for customization:
| Option      | Type      |                                                                                                                                       | …
=> List View Components

http/onboarding.go, http/platform_handler.go, http/swagger.yml
https://github.com/influxdata/platform/pull/592
didn't add /setup endpoint, this pr will do that, also with some swagger fixes
=> fix /setup endpoint

query/README.md
Closes #912 
Update flux specification location to the flux repository.
Link was not updated during the move.
The link now points to the `master` spec.
=> fix(query/docs): update Flux spec to flux repo

http/platform_handler.go
Quick fix for fields that were accidentally not set
=> fix(http): add {Authorization,Session}Service to AuthenticationHandler

cmd/influx/setup.go
Closes #941 
Regular input with go scanner won't have problems to use Ctrl+C to cancel. The only complicated part is the password. We use  crypo/ssh/terminal ReadPassword, so the password won't echo when typing, and the cursor moves correctly.
For the time being, I just reserve the word `cancel` to do the terminate the process.
=> use cancel text

cmd/influxd/extra.go, cmd/influxd/main.go, go.sum, http/api_handler.go, http/write_handler.go, nats/engine_handler.go, tsdb/engine.go, tsdb/explode.go, tsdb/shard.go
This PR is intended to be a sufficient first step to allow people to play with influxd and have it read and write data.
It hooks up an initial storage engine to the influxd binary. It can be used to read and write data. Future changes will be to either eliminate all of the code in extra.go or move it to a better location, as well as make it so that we have an appropriate WAL or whatever to avoid snapshotting the cache on every write.
Closes #898
Closes #899
=> Storage engine integration

usage.go
Closes #
Add query metrics to usage endpoint.
Usage endpoint did not have query metrics exposed
Add the named query constants.
=> feat(usage): add query usage metrics

cmd/influx/setup.go
Closes # https://github.com/influxdata/platform/issues/972
remove default username admin, user has to type the username
=> remove default username

cmd/influx/setup.go
Closes #https://github.com/influxdata/platform/issues/971
=> add confimation scene

chronograf/ui/src/onboarding/containers/SigninPage.tsx
Rather than so a message to reload the browser on login, reload the page after success
=> Reload page on sign in

chronograf/ui/src/flux/components/v2/FluxEditor.test.tsx, chronograf/ui/src/flux/components/v2/FluxEditor.tsx
=> Move flux editor over to v2

http/api_handler.go, http/bucket_service.go, http/dashboard_service.go, http/org_service.go, http/task_service.go, http/user_resource_mapping_service.go, user_resource_mapping.go
=> Add owner/member endpoints for tasks

http/api_handler.go, http/swagger.yml, http/user_service.go
Returns the currently signed in user from session or token
=> Add a me endpoint for chronograf

cmd/influx_inspect/buildtsi/buildtsi.go, tsdb/tsm1/cache.go
We need this for other projects importing the engine. Note, it _does not_ provide the logic for the inspect binary. That needs to follow in a future PR.
=> Add skeleton buildtsi

chronograf/ui/src/clockface/components/form_layout/Form.tsx, chronograf/ui/src/flux/components/v2/FluxEditor.test.tsx, chronograf/ui/src/index.tsx, chronograf/ui/src/shared/apis/v2/organization.ts, chronograf/ui/src/shared/apis/v2/user.ts, chronograf/ui/src/shared/copy/v2/notifications.ts, chronograf/ui/src/store/configureStore.js, chronograf/ui/src/tasks/actions/v2/index.ts, chronograf/ui/src/tasks/api/v2/index.ts, chronograf/ui/src/tasks/containers/TaskPage.tsx, chronograf/ui/src/tasks/containers/TasksPage.tsx, chronograf/ui/src/tasks/reducers/v2/index.ts
Closes #958 
Basic UI for creating a task that belongs to the user
=> Basic task creation ui

chronograf/ui/src/onboarding/components/AdminStep.tsx, chronograf/ui/src/onboarding/components/CompletionStep.tsx, chronograf/ui/src/onboarding/components/InitStep.tsx
=> Update onboarding copy

telegraf.go
Closes #https://github.com/influxdata/platform/issues/944
=> add telegraf.go

telegraf/plugins/inputs/cpu.go, telegraf/plugins/inputs/disk.go, telegraf/plugins/inputs/diskio.go, telegraf/plugins/inputs/docker.go, telegraf/plugins/inputs/file.go, telegraf/plugins/inputs/inputs_test.go, telegraf/plugins/inputs/kernel.go, telegraf/plugins/inputs/kubernetes.go, telegraf/plugins/inputs/logparser.go, telegraf/plugins/inputs/mem.go, telegraf/plugins/inputs/net.go, telegraf/plugins/inputs/net_response.go, telegraf/plugins/inputs/ngnix.go, telegraf/plugins/inputs/processes.go, telegraf/plugins/inputs/procstats.go, telegraf/plugins/inputs/prometheus.go, telegraf/plugins/inputs/redis.go, telegraf/plugins/inputs/swap.go, telegraf/plugins/inputs/syslog.go, telegraf/plugins/inputs/system.go, telegraf/plugins/inputs/tail.go, telegraf/plugins/outputs/file.go, telegraf/plugins/outputs/influxdb_v2.go, telegraf/plugins/outputs/outputs_test.go
Closes #https://github.com/influxdata/platform/issues/1007
=> add plugins

chronograf/ui/src/pageLayout/containers/Nav.tsx, chronograf/ui/src/shared/copy/v2/notifications.ts, chronograf/ui/src/tasks/actions/v2/index.ts, chronograf/ui/src/tasks/api/v2/index.ts, chronograf/ui/src/tasks/components/TaskRow.tsx, chronograf/ui/src/tasks/components/TasksHeader.tsx, chronograf/ui/src/tasks/components/TasksList.tsx, chronograf/ui/src/tasks/containers/TaskPage.tsx, chronograf/ui/src/tasks/containers/TasksPage.tsx, chronograf/ui/src/tasks/reducers/v2/index.ts, chronograf/ui/src/types/v2/tasks.ts
=> List tasks in UI

http/swagger.yml
Closes #https://github.com/influxdata/platform/issues/946
#https://github.com/influxdata/platform/issues/1010
=> draft of telegraf

bolt/bbolt.go, bolt/telegraf.go, bolt/telegraf_test.go, bolt/user_resource_mapping.go, inmem/service.go, inmem/telegraf.go, inmem/telegraf_test.go, inmem/user_resource_mapping_service.go, telegraf.go, testing/telegraf.go, user_resource_mapping.go
Closes #https://github.com/influxdata/platform/issues/945
- mostly common crud
- fixed a small issue for inmem/user_resource_mapping filter func, which is inconsistent with bolt. 
when the filter has multiple requirements.
- add new user resource mapping for telegraf
- add some helper method in user resource mapping
=> add telegraf store service

context/token.go, http/query_handler.go, http/task_service.go
=> refactor(token): remove context token

chronograf/ui/src/onboarding/containers/OnboardingWizard.tsx
=> Take user to completion page on skip

chronograf/ui/src/tasks/components/TaskRow.tsx, chronograf/ui/src/tasks/components/TasksList.tsx
=> Add Task row component to avoid higher order functions in component

bolt/dashboard.go, dashboard.go, http/dashboard_test.go, http/swagger.yml, inmem/dashboard.go, inmem/dashboard_test.go, testing/dashboards.go
Add descriptions to dashboards
Dashboards now have descriptions
=>  feat(dashboard): add description fields to dashboard 

usage.go
Add usage values and usage series metrics
Add place holders for storage metrics exposed via the usage API
=> feat(usage): add values and series metrics to usage service

tsdb/tsm1/batch_float.go, tsdb/tsm1/batch_float_test.go
This PR pulls in the work done in influxdata/influxdb#10362 to improve performance of the TSM batch-oriented float decoder.
=> Improved performance of batch float decoder

chronograf/ui/src/index.tsx, chronograf/ui/src/shared/copy/v2/notifications.ts, chronograf/ui/src/tasks/actions/v2/index.ts, chronograf/ui/src/tasks/api/v2/index.ts, chronograf/ui/src/tasks/components/TaskForm.tsx, chronograf/ui/src/tasks/components/TaskHeader.tsx, chronograf/ui/src/tasks/components/TaskRow.tsx, chronograf/ui/src/tasks/components/TasksList.tsx, chronograf/ui/src/tasks/containers/TaskEditPage.tsx, chronograf/ui/src/tasks/containers/TasksPage.tsx, chronograf/ui/src/tasks/reducers/v2/index.ts, chronograf/ui/src/types/v2/tasks.ts
=> User can update a task

models/points.go
Export models.UnescapeMeasurement
Needed models.UnescapeMeasurement in idpe
Capitalize the letter "U".
=> Export models.UnescapeMeasurement

storage/reads/array_cursor.gen.go, storage/reads/array_cursor.gen.go.tmpl
=> Fix panic when performing filters on value data

cmd/influx/main.go, cmd/influx/write.go, http/write_handler.go, http/write_handler_test.go, mock/points_writer.go, mock/write_service.go, write.go, write/batcher.go, write/batcher_test.go
Closes #1025 
Closes #1026 
Add an HTTP write client and write to the CLI program.
We had neither
added client, tests and mock of points writer.
=>  feat(http): add http write client 

go.mod, telegraf.go, telegraf/plugins/inputs/cpu.go, telegraf/plugins/inputs/disk.go, telegraf/plugins/inputs/diskio.go, telegraf/plugins/inputs/docker.go, telegraf/plugins/inputs/file.go, telegraf/plugins/inputs/inputs_test.go, telegraf/plugins/inputs/kernel.go, telegraf/plugins/inputs/kubernetes.go, telegraf/plugins/inputs/logparser.go, telegraf/plugins/inputs/mem.go, telegraf/plugins/inputs/net.go, telegraf/plugins/inputs/net_response.go, telegraf/plugins/inputs/ngnix.go, telegraf/plugins/inputs/processes.go, telegraf/plugins/inputs/procstats.go, telegraf/plugins/inputs/prometheus.go, telegraf/plugins/inputs/redis.go, telegraf/plugins/inputs/swap.go, telegraf/plugins/inputs/syslog.go, telegraf/plugins/inputs/system.go, telegraf/plugins/inputs/tail.go, telegraf/plugins/outputs/file.go, telegraf/plugins/outputs/influxdb_v2.go, telegraf/plugins/outputs/outputs_test.go, telegraf_test.go
Closes #https://github.com/influxdata/platform/issues/948
=> add toml for telegraf

ui/src/clockface/components/Button/index.tsx, ui/src/clockface/index.ts, ui/src/clockface/types/index.ts, ui/src/onboarding/components/AdminStep.tsx, ui/src/onboarding/components/CompletionStep.tsx, ui/src/onboarding/components/InitStep.tsx, ui/src/onboarding/components/OtherStep.tsx, ui/src/onboarding/containers/OnboardingWizard.tsx
Add password confirmation field
Cursor defaults to username field
Enter submits wizard steps
Closes #1084 #1088 #1085
=> Onboarding wizard polish

cmd/influxd/main.go, http/task_service.go, http/task_test.go, task.go, task/backend/coordinator/coordinator.go, task/backend/scheduler.go, task/backend/scheduler_test.go, task/mock/scheduler.go, task/platform_adapter.go, task/servicetest/servicetest.go
This should allow you to cancel runs.
It makes breaking changes to tasks, so will need some work in IDPE as well.
=> Now you can cancel runs

storage/reads/datatypes/storage_common.pb.go, storage/series_cursor.go, tsdb/defaults/defaults.go, tsdb/tsm1/engine.go
Small formatting fixes for master
=> chore(fmt): update formating with make fmt

auth.go, authz.go, bolt/telegraf.go, cmd/influxd/main.go, http/api_handler.go, http/telegraf.go, inmem/telegraf.go, session.go, telegraf.go, telegraf_test.go
Closes #https://github.com/influxdata/platform/issues/947
change http json api to camel cases
add http handlers
=> add http for telegraf

http/swagger.yml, http/telegraf.go
Closes #https://github.com/influxdata/platform/issues/1236
=> fix telegraf sources

http/telegraf.go
=> fix(http): use json decoder to decode request body

ui/src/tasks/api/v2/index.ts
=> Fix api calls for tasks, tasks are now nested in response

http/telegraf.go
Closes https://github.com/influxdata/platform/issues/1255
manual tested
=> (fix/http) replace space with _

http/swagger.yml, http/user_service.go
Closes https://github.com/influxdata/platform/issues/1214
fixed all user response as well
=> fix user response

http/errors.go
Closes https://github.com/influxdata/platform/issues/1237
make the error encode be able to support both new errors lib and old kerrors for now.
=> (fix/http): make error compatible with new and old lib

http/errors.go
based on review of
https://github.com/influxdata/platform/pull/1273
=> fix the error code for 400

tsdb/tsm1/batch_timestamp.go, tsdb/tsm1/compact.gen.go, tsdb/tsm1/compact.gen.go.tmpl, tsdb/tsm1/compact.go
Port of influxdata/influxdb#10431.
=> Fix TSM index maxtime modification

query/influxql/spectests/show_tag_values.go, query/influxql/spectests/show_tag_values_in_list.go, query/influxql/spectests/show_tag_values_multiple_measurements.go, query/influxql/transpiler.go
=> fix: show tag values must specify a range stop

tsdb/config.go, tsdb/index.go, tsdb/index_test.go, tsdb/tsm1/engine_test.go
=>  remove RegisteredIndexes method

http/user_service.go
Me endpoint embedded the response in a me field.  Should be top-level
User object is at top-level of me response now.
=> fix(http): user response of me at top-level

cmd/influx/main.go, cmd/influx/setup.go
Closes https://github.com/influxdata/platform/issues/1264
manually tested
=> (feat/cmd): store token in default location

ui/src/dashboards/constants/cellEditor.ts, ui/src/shared/actions/v2/timeMachines.ts, ui/src/shared/components/ColorScaleDropdown.tsx, ui/src/shared/components/TimeMachineBottom.tsx, ui/src/shared/components/view_options/LineOptions.tsx, ui/src/shared/components/view_options/OptionsSwitcher.tsx, ui/src/shared/components/view_options/ViewOptions.tsx, ui/src/shared/components/view_options/options/ColorSelector.tsx, ui/src/shared/components/view_options/options/DecimalPlaces.tsx, ui/src/shared/components/view_options/options/YAxisAffixes.tsx, ui/src/shared/components/view_options/options/YAxisBase.tsx, ui/src/shared/components/view_options/options/YAxisBound.tsx, ui/src/shared/components/view_options/options/YAxisBounds.tsx, ui/src/shared/components/view_options/options/YAxisScale.tsx, ui/src/shared/components/view_options/options/YAxisTitle.tsx, ui/src/shared/reducers/v2/timeMachines.ts
Connect https://github.com/influxdata/platform/issues/1038
Add in initial unstyled ui for display options in the veo.
=> Add display options ui for line graph types

tsdb/explode_test.go
#1345 was opened to make the implementation more efficient, so I wrote these tests to double check it during review. Might as well get them into the code base.
=> test(tsdb): add test for explode points

ui/src/tasks/components/TasksList.tsx
Closes #1371 
_What was the solution?_ Updated Task List column headers to be capitalized
=> Capitalized columns names on the tasks list page

ui/src/organizations/components/Tasks.tsx, ui/src/tasks/actions/v2/index.ts, ui/src/tasks/api/v2/index.ts, ui/src/tasks/components/TaskRow.tsx, ui/src/tasks/components/TasksList.tsx, ui/src/tasks/containers/TasksPage.tsx, ui/src/types/v2/tasks.ts
Co-authored-by: Palak Bhojani <patel.palak41@gmail.com>
Closes #1327 
Added a toggle button on the Tasks Page and created an API call function for updating the task status on toggle change
=> Add enable toggle feature to tasks page

ui/src/organizations/components/Tasks.tsx, ui/src/tasks/components/TaskRow.tsx, ui/src/tasks/components/TasksList.tsx, ui/src/types/v2/tasks.ts
Closes #1367 
A new feature to be added to the tasks page. Created a new column for schedule and added the every, delay and cron to task type definition.
=> Added schedule column to the tasks page

ui/src/pageLayout/PageLayout.scss, ui/src/pageLayout/components/Page.scss, ui/src/pageLayout/components/PageContents.tsx, ui/src/pageLayout/containers/Nav.tsx, ui/src/style/_variables.scss, ui/src/style/chronograf.scss
Adds a slight margin between the nav bar and full-width pages
Imports page styles into navbar component (because it's on every page)
=> Polish Page Styles

tsdb/explode.go
Closes #
This PR is to reduce parsing and copying of tags in `ExplodePoints`.
=> reduce parsing and copying of tags

cmd/influxd/main.go, cmd/influxd/main_test.go, http/query.go, http/query_handler_test.go, http/query_test.go
Adds integration testing and an end-to-end write+query test.
We don't have any integration tests.
Add an integration test.
=> Add end-to-end write/query integration testing.

ui/src/organizations/components/OrganizationsIndexContents.tsx
This fixes the misalignment of the page
=> Fix Alignment of Orgs Index View

ui/src/shared/copy/v2/notifications.ts, ui/src/tasks/actions/v2/index.ts
Closes #1368 
_What was the solution?_ Added additional message on the notification for task not created
=> Add error message on task not created error

ui/src/shared/components/search_widget/SearchWidget.tsx, ui/src/tasks/components/TaskHeader.tsx, ui/src/tasks/components/TasksHeader.tsx, ui/src/tasks/components/TasksOrgDropdown.tsx, ui/src/tasks/components/TasksPage.scss
Closes #
_What was the problem?_ The tasks header was messy with many components
_What was the solution?_ The css changed the div into label and decremented pixels on dropdown and search widget
=> Fix css on tasks header for cleaner view

ui/src/onboarding/actions/dataSources.ts, ui/src/onboarding/actions/steps.ts, ui/src/onboarding/components/ConfigureDataSourceStep.tsx, ui/src/onboarding/components/ConfigureDataSourceSwitcher.tsx, ui/src/onboarding/components/DataSourceSelector.tsx, ui/src/onboarding/components/OnboardingStepSwitcher.tsx, ui/src/onboarding/components/SelectDataSourceStep.tsx, ui/src/onboarding/components/StreamingDataSourcesSelector.tsx, ui/src/onboarding/containers/OnboardingWizard.tsx, ui/src/onboarding/reducers/dataSources.ts, ui/src/onboarding/reducers/index.ts, ui/src/onboarding/reducers/steps.ts, ui/src/types/v2/dataSources.ts
Closes #1422 
Add step for choosing csv, streaming or line protocol. If you choose streaming,  you can add the different streaming data source options.
=> feat(ui/onboarding): Add step for choosing csv, streaming, or line protocol

auth.go, bolt/authorization.go, bolt/authorization_test.go, bolt/basic_auth_service.go, bolt/bbolt.go, bolt/user.go, errors.go, errors_test.go, http/auth_service.go, http/auth_test.go, http/authentication_middleware.go, http/errors.go, http/user_service.go, inmem/auth_service.go, inmem/auth_test.go, inmem/service.go, inmem/user_service.go, testing/auth.go, testing/macro.go, testing/user_service.go, testing/util.go
Closes https://github.com/influxdata/platform/issues/1290
convert the http /authorization endpoint output based on specs of swagger doc.
prerequisite: https://github.com/influxdata/idpe/pull/1966
=> fix(http): convert auth errors

ui/src/api/api.ts, ui/src/tasks/actions/v2/index.ts, ui/src/tasks/api/v2/index.ts
=> Switch Tasks UI updates to use generated client

bolt/bucket.go, bolt/onboarding.go, bolt/session.go, bolt/user_resource_mapping.go, http/api_handler.go, http/query.go, http/query_handler.go, http/query_test.go, http/write_handler.go, query/bridges.go, query/logger.go, query/request.go, task/backend/query_logreader.go, user_resource_mapping.go
Closes #1467 
This PR introduces a mechanism for turning a user resource mapping into a set of permissions that can be used to authorize requests. Additionally, it removes the write endpoints dependence on the authorization service and uses the authorizer middleware instead.
=> Fix issue#1467

http/cur_swagger.yml, ui/src/api/api.ts, ui/src/tasks/actions/v2/index.ts, ui/src/tasks/api/v2/index.ts
=> Switch Task UI get tasks to use generated client

ui/src/tasks/api/v2/index.ts, ui/src/utils/api.ts
=> Move api initialization to util

http/cur_swagger.yml, ui/src/api/api.ts, ui/src/tasks/api/v2/index.ts
=> Fixes tasks request for frontend

ui/src/dashboards/components/ImportDashboardOverlay.tsx, ui/src/shared/copy/v2/notifications.ts, ui/src/tasks/actions/v2/index.ts, ui/src/tasks/components/ImportTaskOverlay.test.tsx, ui/src/tasks/components/ImportTaskOverlay.tsx, ui/src/tasks/components/TaskRow.tsx, ui/src/tasks/components/TasksHeader.tsx, ui/src/tasks/components/__snapshots__/ImportTaskOverlay.test.tsx.snap, ui/src/tasks/containers/TasksPage.test.tsx, ui/src/tasks/containers/TasksPage.tsx, ui/src/tasks/containers/__snapshots__/TasksPage.test.tsx.snap
Closes #1471 
_What was the solution?_ Added import button on task header to import the task using flux script and also created tests for the import function which created the snapshot
=> Import on Tasks Page for flux script

query/functions/query_test.go
Fixes #1338 .
Generated end-to-end tests now compare tables directly instead of serializing to JSON first and then comparing.
Serializing query results to JSON and then doing a byte-for-byte comparison agains actual vs expected results was failing if there were any small differences in floating point values.
Perform the comparison on the tables themselves (before serialization) using comparison methods that allow for floating point tolerance.
=> table comparisons for generated end-to-end tests

http/cur_swagger.yml, ui/mocks/dummyData.ts, ui/src/api/api.ts, ui/src/dashboards/actions/v2/index.ts, ui/src/dashboards/apis/v2/index.ts, ui/src/dashboards/components/DashboardHeader.tsx, ui/src/dashboards/components/DashboardPage.tsx, ui/src/dashboards/components/dashboard_empty/DashboardEmpty.tsx, ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx, ui/src/dashboards/components/dashboard_index/Table.tsx, ui/src/dashboards/constants/index.ts, ui/src/dashboards/reducers/v2/dashboards.ts, ui/src/dashboards/resources.ts, ui/src/dashboards/utils/cellGetters.ts, ui/src/dashboards/utils/dashboardSwitcherLinks.ts, ui/src/shared/components/cells/Cells.tsx, ui/src/types/apis/dashboards.ts, ui/src/types/index.ts, ui/src/types/v2/dashboards.ts, ui/src/types/v2/index.ts, ui/src/utils/api.ts
=> Switch Dashboard UI to use generated client

ui/.npmrc
This is to workaround a yarn bug,
https://github.com/yarnpkg/yarn/issues/6312
=> Deal with yarn bug

http/task_service.go
=> fix(http/task): add validation for beforeTime/afterTime params

bolt/bucket.go, bolt/bucket_test.go, bucket.go, cmd/influx/bucket.go, http/bucket_service.go, http/bucket_test.go, inmem/bucket_service.go, inmem/bucket_test.go, testing/bucket_service.go
Reverts influxdata/platform#1567
=> Revert "convert /buckets endpoint error to platform error "

ui/mocks/dummyData.ts, ui/src/onboarding/OnboardingWizard.scss, ui/src/onboarding/actions/dataLoaders.ts, ui/src/onboarding/components/ConfigureDataSourceStep.tsx, ui/src/onboarding/components/ConfigureDataSourceSwitcher.tsx, ui/src/onboarding/components/DataSourceTypeSelector.tsx, ui/src/onboarding/components/OnboardingSideBar.test.tsx, ui/src/onboarding/components/OnboardingSideBar.tsx, ui/src/onboarding/components/OnboardingStepSwitcher.tsx, ui/src/onboarding/components/SelectDataSourceStep.tsx, ui/src/onboarding/components/__snapshots__/OnboardingSideBar.test.tsx.snap, ui/src/onboarding/components/side_bar/SideBar.scss, ui/src/onboarding/components/side_bar/SideBar.test.tsx, ui/src/onboarding/components/side_bar/SideBar.tsx, ui/src/onboarding/components/side_bar/SideBarButton.test.tsx, ui/src/onboarding/components/side_bar/SideBarButton.tsx, ui/src/onboarding/components/side_bar/SideBarTab.test.tsx, ui/src/onboarding/components/side_bar/SideBarTab.tsx, ui/src/onboarding/components/side_bar/__snapshots__/SideBar.test.tsx.snap, ui/src/onboarding/components/side_bar/__snapshots__/SideBarButton.test.tsx.snap, ui/src/onboarding/components/side_bar/__snapshots__/SideBarTab.test.tsx.snap, ui/src/onboarding/containers/OnboardingWizard.tsx, ui/src/onboarding/reducers/dataLoaders.test.ts, ui/src/onboarding/reducers/dataLoaders.ts, ui/src/onboarding/utils/dataLoaders.ts, ui/src/types/v2/dataSources.ts
Closes #1579 
Creates new onboarding sidepanel component. (thanks @alexpaxton!) and uses it to display selected data sources that can be later configured.
=> Datasources sidepanel

bolt/bucket.go, bolt/bucket_test.go, bucket.go, cmd/influx/bucket.go, http/bucket_service.go, http/bucket_test.go, inmem/bucket_service.go, inmem/bucket_test.go, testing/bucket_service.go
Reverts influxdata/platform#1626
=> re-enable convert /buckets endpoint error to platform error ""

.circleci/config.yml, .gitignore, chronograf/.gitignore, chronograf/README.md, chronograf/docs/slides/mnGo/Makefile, chronograf/etc/Dockerfile_build, chronograf/etc/build.py, ui/Makefile, ui/README.md, ui/package-lock.json, ui/package.json
=> Remove yarn from project in favor of just npm

ui/src/dashboards/actions/v2/index.ts, ui/src/dashboards/actions/v2/notes.ts, ui/src/dashboards/actions/v2/views.ts, ui/src/dashboards/apis/v2/index.ts, ui/src/dashboards/apis/v2/view.ts, ui/src/dashboards/components/DashboardPage.tsx, ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx, ui/src/dashboards/reducers/v2/views.ts, ui/src/logs/actions/index.ts, ui/src/logs/containers/logs_page/LogsPage.tsx, ui/src/logs/utils/config.ts, ui/src/shared/actions/v2/me.ts, ui/src/shared/components/cells/Cell.tsx, ui/src/shared/components/cells/View.tsx, ui/src/types/v2/dashboards.ts, ui/src/utils/api.ts
=> Switch views request to use generated client

ui/package-lock.json
=> Resolve package-lock.json conflicts

ui/src/clockface/components/inputs/TextArea.scss, ui/src/clockface/components/inputs/TextArea.tsx, ui/src/onboarding/actions/dataLoaders.ts, ui/src/onboarding/components/configureStep/ConfigureDataSourceStep.tsx, ui/src/onboarding/components/configureStep/ConfigureDataSourceSwitcher.tsx, ui/src/onboarding/components/configureStep/lineProtocol/LineProtocolTabs.test.tsx, ui/src/onboarding/components/configureStep/lineProtocol/LineProtocolTabs.tsx, ui/src/onboarding/components/configureStep/lineProtocol/__snapshots__/LineProtocol.test.tsx.snap, ui/src/onboarding/components/configureStep/lineProtocol/__snapshots__/LineProtocolTabs.test.tsx.snap, ui/src/onboarding/reducers/dataLoaders.test.ts, ui/src/onboarding/reducers/dataLoaders.ts
Closes #1480 
Added new clockface component for TextArea input, updated LineProtocol activeTab and lineProtocolText to redux state
=> Add option for enter manually on line protocol configuration.

ui/src/onboarding/components/configureStep/lineProtocol/LineProtocolTabs.tsx, ui/src/onboarding/components/configureStep/lineProtocol/__snapshots__/LineProtocolTabs.test.tsx.snap
Closes #1479
Add input form element for File URL line protocol configuration
=> Add File URL option for line protocol

bolt/organization.go, bolt/organization_test.go, cmd/influx/organization.go, http/org_service.go, http/org_test.go, inmem/organization_service.go, inmem/organization_test.go, organization.go, testing/organization_service.go
Closes #https://github.com/influxdata/platform/issues/1293
=> fix(http): convert org errors endpoint

http/cur_swagger.yml, ui/src/api/api.ts, ui/src/onboarding/actions/dataLoaders.ts, ui/src/onboarding/apis/index.ts, ui/src/onboarding/components/configureStep/ConfigureDataSourceStep.tsx, ui/src/onboarding/components/configureStep/ConfigureDataSourceSwitcher.tsx, ui/src/onboarding/components/configureStep/lineProtocol/LineProtocol.test.tsx, ui/src/onboarding/components/configureStep/lineProtocol/LineProtocol.tsx, ui/src/onboarding/components/configureStep/lineProtocol/LineProtocolTabs.test.tsx, ui/src/onboarding/components/configureStep/lineProtocol/LineProtocolTabs.tsx, ui/src/onboarding/components/configureStep/lineProtocol/__snapshots__/LineProtocol.test.tsx.snap, ui/src/shared/copy/v2/notifications.ts, ui/src/utils/api.ts
Closes #1482 
Add the ability to upload file
=> Add ability to file upload and call write api

ui/src/Setup.tsx, ui/src/index.tsx, ui/src/onboarding/actions/steps.ts, ui/src/onboarding/components/configureStep/ConfigureDataSourceStep.tsx, ui/src/onboarding/components/selectionStep/SelectDataSourceStep.tsx, ui/src/onboarding/containers/OnboardingWizard.tsx, ui/src/onboarding/containers/OnboardingWizardPage.tsx, ui/src/onboarding/reducers/steps.ts, ui/src/onboarding/utils/index.ts
=> Handling onboarding with react router

ui/src/onboarding/components/verifyStep/ConnectionInformation.tsx, ui/src/onboarding/components/verifyStep/__snapshots__/ConnectionInformation.test.tsx.snap
=> Load and clear -> Loud and clear

http/swagger.yml
=> doc(http): delete a bucket

http/cur_swagger.yml, ui/src/api/api.ts, ui/src/logs/containers/logs_page/LogsPage.tsx, ui/src/logs/utils/logQuery.test.ts, ui/src/shared/apis/v2/queryBuilder.ts, ui/src/shared/components/TimeMachineQueryBuilder.tsx, ui/src/shared/containers/SetActiveSource.tsx, ui/src/sources/actions/index.ts, ui/src/sources/apis/index.ts, ui/src/sources/components/CreateSourceOverlay.tsx, ui/src/sources/components/SourcesListRow.tsx, ui/src/types/logs.ts, ui/src/types/v2/index.ts, ui/src/utils/api.ts
=> Move sources to use generated client

http/cur_swagger.yml
=> Document endpoints used by the front end

http/macro_service.go, http/macro_test.go, http/swagger.yml
=> fix(http): don't panic if an invalid macro id is requested

http/bucket_service.go, inmem/organization_service.go, testing/bucket_service.go, testing/organization_service.go, testing/util.go
=> fix(testing): compare expected error messages against actual

bolt/basic_auth_service.go, bolt/session.go, bolt/user.go, bolt/user_test.go, http/user_service.go, http/user_test.go, inmem/user_service.go, inmem/user_test.go, testing/user_service.go, user.go
Closes https://github.com/influxdata/platform/issues/1300
=> fix(http): convert user errors

ui/package-lock.json, ui/src/clockface/components/auto_input/AutoInput.tsx, ui/src/dashboards/constants/index.ts, ui/src/shared/components/ColorDropdown.scss, ui/src/shared/components/ColorDropdown.tsx, ui/src/shared/components/Gauge.tsx, ui/src/shared/components/GaugeChart.test.tsx, ui/src/shared/components/GaugeChart.tsx, ui/src/shared/components/TimeMachine.scss, ui/src/shared/components/TimeMachineFluxEditor.tsx, ui/src/shared/components/TimeMachineQueries.scss, ui/src/shared/components/TimeMachineQueryTab.scss, ui/src/shared/components/view_options/ViewOptions.scss, ui/src/shared/components/view_options/options/DecimalPlaces.tsx, ui/src/shared/reducers/v2/timeMachines.ts
Closes #1822 
Closes #1820
Closes #1823
A few small enhancements to various visualization options. Additional details are in the commit messages.
=> Visualization option enhancements

ui/src/logs/actions/index.ts, ui/src/logs/containers/logs_page/LogsPage.tsx
=> Update readSource usages in log viewer

http/cur_swagger.yml, ui/src/api/api.ts, ui/src/me/apis/index.ts, ui/src/me/components/Settings.tsx, ui/src/onboarding/apis/index.ts, ui/src/onboarding/components/AdminStep.tsx, ui/src/onboarding/containers/SigninPage.tsx, ui/src/shared/actions/v2/me.ts, ui/src/shared/apis/v2/user.ts, ui/src/tasks/actions/v2/index.ts, ui/src/utils/api.ts
=> Use generated client for users endpoints

http/cur_swagger.yml, ui/package-lock.json, ui/src/api/api.ts
Signin doesnt take parameters, it takes basic auth.
Use basic auth
=> Fix(ui/onboarding): Fix signin

ui/mocks/dummyData.ts, ui/src/onboarding/actions/dataLoaders.ts, ui/src/onboarding/apis/index.ts, ui/src/onboarding/apis/mocks.ts, ui/src/onboarding/apis/onboarding.test.ts, ui/src/onboarding/components/OnboardingStepSwitcher.tsx, ui/src/onboarding/components/selectionStep/SelectDataSourceStep.tsx, ui/src/onboarding/components/selectionStep/StreamingSelector.tsx, ui/src/onboarding/components/selectionStep/TypeSelector.tsx, ui/src/onboarding/constants/pluginConfigs.ts, ui/src/onboarding/containers/OnboardingWizard.tsx, ui/src/onboarding/reducers/dataLoaders.test.ts, ui/src/onboarding/reducers/dataLoaders.ts, ui/src/onboarding/utils/pluginConfigs.test.ts, ui/src/onboarding/utils/pluginConfigs.ts, ui/src/types/v2/dataLoaders.ts
Closes #1655
Instead of individually adding plugins, users will select a bundle of plugins.
=> Feat(ui/dataLoaders): Change plugin selection to bundle selection

ui/src/onboarding/components/verifyStep/ConnectionInformation.test.tsx, ui/src/onboarding/components/verifyStep/ConnectionInformation.tsx, ui/src/onboarding/components/verifyStep/DataListening.tsx
Closes #1646 
Add new timer that is used for counting down every second while the request processes
=> Add the ability to count down timer on listening for data

http/swagger.yml
=> docs(http): update authorization definition

bolt/macro.go, bolt/macro_test.go, http/macro_service.go, http/macro_test.go, inmem/macro.go, inmem/macro_test.go, macro.go, testing/macro.go, testing/util.go
=> fix(http): convert macro errors

ui/src/onboarding/OnboardingWizard.scss, ui/src/onboarding/components/verifyStep/TelegrafInstructions.tsx, ui/src/onboarding/components/verifyStep/__snapshots__/TelegrafInstructions.test.tsx.snap
Closes #1645 
Create a copy button to copy the code snippet to clipboard.
=> Add ability to copy text to clipboard on Data Listening

http/cur_swagger.yml, ui/src/api/api.ts, ui/src/logs/actions/index.ts, ui/src/logs/components/LogsHeader.tsx, ui/src/logs/containers/logs_page/LogsPage.tsx, ui/src/logs/utils/logQuery.ts, ui/src/shared/apis/v2/buckets.ts, ui/src/types/logs.ts, ui/src/utils/api.ts
=> Switch buckets ui to use generated client

ui/src/index.tsx, ui/src/onboarding/containers/OnboardingWizard.tsx
=> Send the user to the dashboard page after completing onboarding

ui/mocks/dummyData.ts, ui/src/onboarding/components/AdminStep.tsx, ui/src/onboarding/components/InitStep.tsx, ui/src/onboarding/components/OtherStep.tsx, ui/src/onboarding/components/configureStep/ConfigureDataSourceStep.tsx, ui/src/onboarding/components/selectionStep/SelectDataSourceStep.tsx, ui/src/onboarding/components/verifyStep/DataListening.test.tsx, ui/src/onboarding/components/verifyStep/DataListening.tsx, ui/src/onboarding/components/verifyStep/DataStreaming.tsx, ui/src/onboarding/components/verifyStep/VerifyDataStep.tsx, ui/src/onboarding/components/verifyStep/VerifyDataSwitcher.test.tsx, ui/src/onboarding/components/verifyStep/VerifyDataSwitcher.tsx, ui/src/onboarding/containers/OnboardingWizard.tsx
Handle setting step status for the select and configure data steps when the user skips the step
=> Handle setting step status when skipping a step

http/cur_swagger.yml, ui/src/api/api.ts, ui/src/me/components/Resources.tsx, ui/src/me/components/account/Tokens.tsx, ui/src/me/components/account/__snapshots__/Account.test.tsx.snap, ui/src/me/components/account/__snapshots__/Tokens.test.tsx.snap, ui/src/me/containers/MePage.tsx, ui/src/organizations/actions/index.ts, ui/src/organizations/apis/index.ts, ui/src/organizations/components/BucketOverlayForm.tsx, ui/src/organizations/components/BucketRow.tsx, ui/src/organizations/components/Buckets.tsx, ui/src/organizations/components/CreateBucketOverlay.tsx, ui/src/organizations/components/CreateOrgOverlay.tsx, ui/src/organizations/components/GetOrgResources.tsx, ui/src/organizations/components/MemberList.tsx, ui/src/organizations/components/Members.tsx, ui/src/organizations/components/OrgOptions.tsx, ui/src/organizations/components/Retention.tsx, ui/src/organizations/components/RetentionDuration.tsx, ui/src/organizations/components/TaskList.tsx, ui/src/organizations/components/Tasks.tsx, ui/src/organizations/components/UpdateBucketOverlay.tsx, ui/src/organizations/containers/OrganizationView.tsx, ui/src/organizations/reducers/orgs.ts, ui/src/shared/components/resource_fetcher/ResourceFetcher.tsx, ui/src/tasks/constants/index.ts, ui/src/tasks/dummyData.ts, ui/src/types/v2/index.ts, ui/src/utils/api.ts
=> Move org resources to use generated client

http/api_handler.go, http/bucket_service.go, http/dashboard_service.go, http/org_service.go, http/swagger.yml, http/task_service.go, http/telegraf.go, http/user_resource_mapping_service.go, http/user_resource_mapping_test.go, http/view_service.go, mock/user_service.go
=> fix(http): Update members/owners endpoints to implement swagger definitions

ui/src/onboarding/components/configureStep/streaming/ArrayFormElement.test.tsx, ui/src/onboarding/components/configureStep/streaming/ArrayFormElement.tsx, ui/src/onboarding/components/configureStep/streaming/ConfigFieldSwitcher.test.tsx, ui/src/onboarding/components/configureStep/streaming/ConfigFieldSwitcher.tsx, ui/src/onboarding/components/configureStep/streaming/PluginConfigForm.tsx, ui/src/onboarding/constants/pluginConfigs.ts, ui/src/onboarding/reducers/dataLoaders.ts, ui/src/shared/components/URIFormElement.test.tsx, ui/src/shared/components/URIFormElement.tsx, ui/src/types/v2/dataLoaders.ts
Closes #1852
Check if fields are required when determining whether or not a config is completed
=> feat(ui/dataLoaders): Check if fields for plugin configuration

http/swagger.yml
=> chore(http): remove authorization header description from swagger

.circleci/config.yml, http/swagger.yml
=> docs(http): put macros/:id endpoint

http/auth_service.go, http/bucket_service.go, http/chronograf_handler.go, http/dashboard_service.go, http/errors.go, http/macro_service.go, http/macro_test.go, http/onboarding.go, http/org_service.go, http/proxy_query_service.go, http/query_handler.go, http/query_service.go, http/router.go, http/router_test.go, http/scraper_service.go, http/session_handler.go, http/source_service.go, http/task_service.go, http/telegraf.go, http/usage_service.go, http/user_service.go, http/view_service.go, http/write_handler.go
=> add custom-404 handler

bolt/scraper.go, bolt/scraper_test.go, http/scraper_service.go, http/scraper_service_test.go, inmem/scraper.go, inmem/scraper_test.go, scraper.go, testing/scraper_target.go
Closes https://github.com/influxdata/platform/issues/1294
=> fix(http): convert scraper target error

http/auth_service.go, http/auth_test.go, http/swagger.yml
=> fix(http): rename auths to authorizations

bolt/dashboard.go, bolt/dashboard_test.go, dashboard.go, http/dashboard_service.go, http/dashboard_test.go, inmem/dashboard.go, inmem/dashboard_test.go, testing/dashboards.go
Closes https://github.com/influxdata/platform/issues/1292
=> fix(http): convert dashboard errors

bolt/label.go, bolt/label_test.go, http/bucket_service.go, http/dashboard_service.go, http/label_service.go, http/org_service.go, http/swagger.yml, http/task_service.go, http/telegraf.go, http/view_service.go, inmem/label_service.go, inmem/label_test.go, label.go, label_test.go, mock/label_service.go, testing/label_service.go, testing/util.go
=> add labels update endpoint and label colors

ui/src/onboarding/apis/index.ts, ui/src/onboarding/apis/mocks.ts
Adds a mock function for testing the Telegraf update function
=> Create mock for telegraf update function

.goreleaser.yml
Update the nightly build publish location to `platform/nightlies`
=> chore(goreleaser.yml): Update nightly build prefix

bolt/dashboard.go, bolt/view.go, bolt/view_test.go, http/telegraf.go, http/view_service.go, http/view_test.go, inmem/view.go, inmem/view_test.go, testing/cells.go, view.go
Closes https://github.com/influxdata/platform/issues/1301
=> Convert view errors

ui/src/clockface/components/spinners/Spinner.tsx, ui/src/onboarding/OnboardingWizard.scss, ui/src/onboarding/components/AdminStep.tsx, ui/src/onboarding/components/__snapshots__/AdminStep.test.tsx.snap, ui/src/onboarding/components/configureStep/streaming/ArrayFormElement.test.tsx, ui/src/onboarding/components/configureStep/streaming/ArrayFormElement.tsx, ui/src/onboarding/components/configureStep/streaming/ConfigFieldSwitcher.tsx, ui/src/onboarding/components/configureStep/streaming/MultipleInput.scss, ui/src/onboarding/components/configureStep/streaming/MultipleInput.test.tsx, ui/src/onboarding/components/configureStep/streaming/MultipleInput.tsx, ui/src/onboarding/components/selectionStep/SelectDataSourceStep.tsx, ui/src/onboarding/components/selectionStep/StreamingSelector.tsx, ui/src/onboarding/components/verifyStep/TelegrafInstructions.tsx, ui/src/shared/components/URIFormElement.tsx
Closes #1966
Update styles in sections of the onboarding wizard
=> More onboarding styles

bolt/label.go, http/swagger.yml, inmem/label_service.go, label.go, label_test.go, testing/label_service.go
Closes #1954
Adds a "properties" bucket to labels, which can be used to store arbitrary key/value pairs for the UI.
=> Label properties

http/swagger.yml
=> docs(http): add OpenTracing span

http/api_handler.go, http/bucket_service.go, http/bucket_test.go, http/dashboard_service.go, http/dashboard_test.go, http/org_service.go, http/org_test.go, http/task_service.go, http/task_service_test.go, http/task_test.go, http/telegraf.go, http/view_service.go, http/view_test.go, mock/user_service.go
=> fix(http): pass user service to handler New function

http/view_service.go
=> fix(http): return http 400 if request data is invalid

http/router.go, http/router_test.go
=> feat(http): add panic handler

cmd/influxd/main.go, http/api_handler.go, http/assets.go, http/platform_handler.go, paging.go
Developer mode is now passed to assets
Closes #2050
=> fix(http): Fix developer mode default

.circleci/config.yml
Revert the  nightly schedule change.
=> chore(ci): Update schedule back to single nightly build

bolt/telegraf.go, http/telegraf.go, inmem/telegraf.go, telegraf.go, telegraf_test.go, testing/telegraf.go
Closes https://github.com/influxdata/platform/issues/1947
replaced by ops log
=> fix(platform): remove creator and time

errors.go, http/errors.go, http/router.go, http/router_test.go, kit/grpc/errors.go
=> feat(http): add MethodNotAllowed handler

.github/PULL_REQUEST_TEMPLATE
I've modified the pull request template so that the template is more appropriate for that status of the project.
=> fix(.github): cleanup the pull request template

http/api_handler.go, http/api_handler_test.go
=> fix(http): replace default-404 handler with custom-404 handler

http/write_handler.go
Closes https://github.com/influxdata/platform/issues/1302
=> fix(http): convert write endpoint error

http/auth_service.go
=> chore(http): remove debug printf

ui/src/onboarding/components/verifyStep/DataStreaming.tsx, ui/src/onboarding/components/verifyStep/TelegrafInstructions.test.tsx, ui/src/onboarding/components/verifyStep/TelegrafInstructions.tsx, ui/src/onboarding/components/verifyStep/VerifyDataStep.tsx, ui/src/onboarding/components/verifyStep/VerifyDataSwitcher.test.tsx, ui/src/onboarding/components/verifyStep/VerifyDataSwitcher.tsx, ui/src/onboarding/components/verifyStep/__snapshots__/TelegrafInstructions.test.tsx.snap
Closes #2038 
Add notify on the component from OnboardingWizard props so notification can display when user copies the snippet token and script.
=> Add notification when text is copied to clipboard

ui/src/onboarding/OnboardingWizard.scss
=> Style copy button to float right in the text area

bolt/source.go, bolt/source_test.go, http/source_service.go, source.go, testing/source.go
Closes https://github.com/influxdata/platform/issues/1296
=> fix(http): convert source errors

ui/mocks/dummyData.ts, ui/package.json, ui/src/clockface/components/inputs/TextArea.tsx, ui/src/clockface/components/radio_buttons/RadioButtons.tsx, ui/src/onboarding/components/configureStep/ConfigureDataSourceStep.tsx, ui/src/onboarding/components/configureStep/lineProtocol/LineProtocol.test.tsx, ui/src/onboarding/components/configureStep/lineProtocol/LineProtocol.tsx, ui/src/onboarding/components/configureStep/lineProtocol/LineProtocolTabs.tsx, ui/src/onboarding/components/configureStep/lineProtocol/Tab.tsx, ui/src/onboarding/components/configureStep/lineProtocol/TabBody.tsx, ui/src/onboarding/components/configureStep/lineProtocol/TabSelector.tsx, ui/src/onboarding/components/configureStep/lineProtocol/__snapshots__/LineProtocol.test.tsx.snap, ui/src/onboarding/components/configureStep/lineProtocol/__snapshots__/LineProtocolTabs.test.tsx.snap, ui/src/onboarding/components/verifyStep/VerifyDataStep.test.tsx, ui/src/onboarding/components/verifyStep/VerifyDataStep.tsx, ui/src/onboarding/components/verifyStep/VerifyDataSwitcher.test.tsx, ui/src/onboarding/components/verifyStep/VerifyDataSwitcher.tsx, ui/src/onboarding/components/verifyStep/lineProtocol/StatusIndicator.test.tsx, ui/src/onboarding/components/verifyStep/lineProtocol/StatusIndicator.tsx, ui/src/onboarding/components/verifyStep/lineProtocol/__snapshots__/StatusIndicator.test.tsx.snap, ui/src/shared/components/DragAndDrop.tsx
=> Add verify step for line protocol onboarding

Makefile, http/Makefile
=> Make client generation optional via ENV variable

ui/src/onboarding/actions/dataLoaders.ts
Closes #2205 
Updated interval for telegraf confg in dataLoaders to 10ms.
=> Update telegraf.conf constant to 10 instead of 15

bolt/bucket.go, inmem/bucket_service.go, testing/bucket_service.go
Closes https://github.com/influxdata/platform/issues/2072
change bolt, inmem, add more testing
=> fix(bolt): check org id exists before create bucket

http/cur_swagger.yml, ui/src/api/api.ts, ui/src/organizations/apis/index.ts, ui/src/organizations/components/MemberList.tsx, ui/src/organizations/components/Members.tsx, ui/src/organizations/containers/OrganizationView.tsx
Closes #1381
Updated cur_swagger to match swagger for get members API to get role. Updated members from User to ResourceOwner to match API. Added a new column on Members List to include the role.
=> Update MembersList to include role column

ui/src/shared/apis/v2/query.ts, ui/src/shared/components/Conditional.tsx, ui/src/shared/components/RefreshingView.tsx, ui/src/shared/components/TimeMachine.tsx, ui/src/shared/components/TimeSeries.tsx, ui/src/shared/components/cells/Cell.tsx, ui/src/shared/utils/queryBuilder.ts
=> Add timeRangeStart variable to queries as preamble

ui/src/shared/components/view_options/LineOptions.tsx
=> Remove y2 options

ui/src/shared/components/RawFluxDataGrid.tsx, ui/src/shared/components/RawFluxDataTable.tsx, ui/src/shared/utils/rawFluxDataTable.ts
=> Do not truncate time fields in raw view

bolt/authorization.go, http/auth_service.go, http/auth_test.go, inmem/auth_service.go, testing/auth.go
Closes https://github.com/influxdata/platform/issues/2234
fixed the update status error, add more testing
=> fix(bolt): fix auth status update error

ui/src/onboarding/OnboardingWizard.scss, ui/src/onboarding/components/selectionStep/StreamingSelector.test.tsx, ui/src/onboarding/components/selectionStep/StreamingSelector.tsx
Closes #2035 
Add filter input to select streaming step in onboarding.
=> feat(ui/onboarding): Allow filtering of plugin bundles

ui/src/shared/components/TimeMachineQueries.tsx, ui/src/shared/reducers/v2/timeMachines.ts
=> Add explicit submit button for query builder

http/cur_swagger.yml, ui/mocks/dummyData.ts, ui/src/api/api.ts, ui/src/tasks/components/TaskRow.test.tsx, ui/src/tasks/components/TaskRow.tsx, ui/src/tasks/components/__snapshots__/TaskRow.test.tsx.snap, ui/src/tasks/components/__snapshots__/TasksList.test.tsx.snap, ui/src/tasks/containers/__snapshots__/TasksPage.test.tsx.snap, ui/src/types/v2/tasks.ts
Closes #1883
Adds labels in task list
=> feat(ui/labels): display labels in task row

ui/src/shared/actions/v2/timeMachines.ts, ui/src/shared/components/TimeMachineQueries.tsx, ui/src/shared/components/TimeMachineQueryTab.tsx, ui/src/shared/reducers/v2/timeMachines.test.ts, ui/src/shared/reducers/v2/timeMachines.ts, ui/src/types/v2/dashboards.ts
=> Allow query builder to toggle query visibility

http/api_handler.go, http/session_handler.go, http/session_test.go
=> initialize session handler by SessionBackend

http/swagger.yml
=> docs(http): remove unused org param from swagger

http/cur_swagger.yml, ui/src/api/api.ts, ui/src/organizations/apis/index.ts, ui/src/organizations/components/BucketList.tsx, ui/src/organizations/components/BucketRow.tsx, ui/src/organizations/components/Buckets.tsx, ui/src/organizations/components/GetOrgResources.tsx, ui/src/organizations/containers/OrganizationView.tsx
Closes #2323 
- Update cur_swagger to match the delete in swagger
- Update bucket row to include new index cell for delete button
- Add action to call the delete api
=> Add delete column and functionality to buckets list and row

http/cur_swagger.yml, ui/src/api/api.ts, ui/src/clockface/components/index_views/IndexList.scss, ui/src/clockface/components/label/Label.scss, ui/src/clockface/components/label/LabelContainer.scss, ui/src/clockface/components/label/LabelContainer.tsx, ui/src/clockface/components/label/LabelSelector.tsx, ui/src/clockface/components/label/LabelSelectorMenu.tsx, ui/src/dashboards/actions/v2/index.ts, ui/src/dashboards/apis/v2/index.ts, ui/src/dashboards/components/EditDashboardLabelsOverlay.tsx, ui/src/dashboards/components/dashboard_index/Contents.tsx, ui/src/dashboards/components/dashboard_index/DashboardsIndex.tsx, ui/src/dashboards/components/dashboard_index/Table.tsx, ui/src/dashboards/components/dashboard_index/TableRow.test.tsx, ui/src/dashboards/components/dashboard_index/TableRow.tsx, ui/src/dashboards/components/dashboard_index/TableRows.tsx, ui/src/dashboards/reducers/v2/dashboards.test.ts, ui/src/dashboards/reducers/v2/dashboards.ts, ui/src/shared/apis/v2/labels.ts, ui/src/shared/components/FetchLabels.tsx, ui/src/shared/copy/notifications.ts, ui/src/style/_variables.scss
Closes #1884 
You will be able to add and remove labels from a dashboard from the dashboard index list.
=> feat(ui/labels): Add the ability to edit labels on a dashboard
